### ISSUE TITLE
Doesn't seem to work with 2FA

### ISSUE THREAD

**Issue by Nimothy** [fastlane/boarding#100]
Deployed a new Heroku app get an error on checking the production logs I see:

```
2016-10-22T07:33:41.782228+00:00 app[web.1]: Please select a device to verify your identity
2016-10-22T07:33:41.783736+00:00 app[web.1]: Completed 500 Internal Server Error in 1105ms
2016-10-22T07:33:41.785151+00:00 app[web.1]: 
2016-10-22T07:33:41.785153+00:00 app[web.1]: NoMethodError (undefined method `choose' for #<Spaceship::TunesClient:0x007fac05456330>):
2016-10-22T07:33:41.785154+00:00 app[web.1]:   app/controllers/invite_controller.rb:160:in `login'
2016-10-22T07:33:41.785154+00:00 app[web.1]:   app/controllers/invite_controller.rb:140:in `app'
2016-10-22T07:33:41.785155+00:00 app[web.1]:   app/controllers/invite_controller.rb:152:in `block in app_metadata'
2016-10-22T07:33:41.785156+00:00 app[web.1]:   app/controllers/invite_controller.rb:165:in `set_app_details'
2016-10-22T07:33:41.785156+00:00 app[web.1]:   app/controllers/invite_controller.rb:150:in `app_metadata'
2016-10-22T07:33:41.785156+00:00 app[web.1]: 
2016-10-22T07:33:41.785157+00:00 app[web.1]: 
```

So it looks like it doesn't work with 2FA, so I generate an app specific password and get the error:

```
2016-10-22T07:29:52.002790+00:00 app[web.1]: Completed 500 Internal Server Error in 183ms
2016-10-22T07:29:52.003282+00:00 app[web.1]: 
2016-10-22T07:29:52.003284+00:00 app[web.1]: Spaceship::Client::InvalidUserCredentialsError (Invalid username and password combination. Used 'da@nineteneleven.org' as the username.):
2016-10-22T07:29:52.003301+00:00 app[web.1]:   app/controllers/invite_controller.rb:160:in `login'
2016-10-22T07:29:52.003302+00:00 app[web.1]:   app/controllers/invite_controller.rb:140:in `app'
2016-10-22T07:29:52.003303+00:00 app[web.1]:   app/controllers/invite_controller.rb:152:in `block in app_metadata'
2016-10-22T07:29:52.003304+00:00 app[web.1]:   app/controllers/invite_controller.rb:150:in `app_metadata'
2016-10-22T07:29:52.003304+00:00 app[web.1]:   app/controllers/invite_controller.rb:165:in `set_app_details'
2016-10-22T07:29:52.003305+00:00 app[web.1]: 
2016-10-22T07:29:52.003306+00:00 app[web.1]: 
2016-10-22T07:29:52.037111+00:00 heroku[router]: at=info method=GET path="/" host=jesusis.herokuapp.com request_id=86a6cd29-0e21-4d29-80ab-fb0bd778c236 fwd="81.141.14.45" dyno=web.1 connect=0ms service=201ms status=500 bytes=1669
```

Any ideas how to resolve without turning of 2FA?

**Comment by KrauseFx** [comment]
Did you modify invite_controller.rb? Where is `choose` being called?

**Comment by Nimothy** [comment]
I made no modifications I tried with just the deploy to Heroku and got these results, when I tried an account without 2FA it worked perfectly.... 

In terms of `choose`, I think that's related to:
```Ruby
    def login
      return if @spaceship
      @spaceship = Spaceship::Tunes.login(user, password)
      @spaceship.select_team
    end
```

Looks like the `choose` is spaceship asking which number I want to use to login via 2FA, it seems there is no way of telling it to use an app specific password...

**Comment by ay8s** [comment]
Think I am seeing the same behaviour after setting up a app specific password.

**Comment by ohwutup** [comment]
Hi everyone,

Thanks for raising the issue... it looks like the `choose` method was a bit of a red herring, and we have added some documentation around getting _boarding_ working with 2FA here: https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification.

That session that you get back from running `spaceauth` will last for a while, but it does still require that you pass the username and password as ENV vars to boarding as well.

Please let us know if you have anymore questions! 
🚀

**Comment by harkmall** [comment]
Probably a dumb question, but how do I pass the session as ENV to my boarding site on heroku? I just followed the steps on the boarding README

**Comment by ohwutup** [comment]
Hey @harkmall, not a dumb question at all! You should be able to set environment variables in the Settings pane of your heroku app and click on `Reveal Config Vars`.

Let us know if you have any more questions! 
![screen_shot_2016-11-14_at_9_32_55_am](https://cloud.githubusercontent.com/assets/2587018/20268592/d33b7da2-aa4d-11e6-9904-3f808b979e11.png)

**Comment by harkmall** [comment]
I did that but I still get the "Something went wrong" error. Its also happening on the demo site as per #104, so maybe its a different issue.

**Comment by ohwutup** [comment]
Would you mind sharing your logs? I am able to get up and running with 2FA in my own testing, so it would be helpful to see your output. Thanks!

**Comment by harkmall** [comment]
```
2016-11-15T00:05:52.730098+00:00 app[web.1]: Two Factor Authentication for account '<email>' is enabled
2016-11-15T00:05:52.748360+00:00 app[web.1]:   app/controllers/invite_controller.rb:163:in `login'
2016-11-15T00:05:52.748360+00:00 app[web.1]:   app/controllers/invite_controller.rb:143:in `app'
2016-11-15T00:05:52.748368+00:00 app[web.1]:   app/controllers/invite_controller.rb:155:in `block in app_metadata'
2016-11-15T00:05:52.748369+00:00 app[web.1]:   app/controllers/invite_controller.rb:153:in `app_metadata'
2016-11-15T00:05:52.748370+00:00 app[web.1]:   app/controllers/invite_controller.rb:168:in `set_app_details'
2016-11-15T00:05:52.748370+00:00 app[web.1]: 
2016-11-15T00:05:52.748371+00:00 app[web.1]: 
2016-11-15T00:05:53.955406+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=movieawks.herokuapp.com request_id=a649e30c-1f7a-4719-be8b-067da315dcf3 fwd="50.100.88.136" dyno=web.1 connect=1ms service=3ms status=304 bytes=48
2016-11-15T00:05:51.460698+00:00 heroku[web.1]: State changed from starting to up```

Those are the logs on my heroku app

**Comment by ay8s** [comment]
I got around this in the end after the tweak to not require an admin account was merged, I now use another account without 2FA enabled.

**Comment by ohwutup** [comment]
@harkmall, are you providing the `ITC_PASSWORD` environment variable when you are running the app?

**Comment by harkmall** [comment]
It is a config var on my heroku app if that's what you mean.

**Comment by ohwutup** [comment]
@harkmall and sorry for the annoying question, but you are running an up-to-date version of _boarding_?

**Comment by harkmall** [comment]
I just followed exactly what it says to do in the "getting started" section of the readme. I also tried doing the "update to a new version" but that didn't exactly work either 😬

**Comment by harkmall** [comment]
Any suggestions on what to do @ohwutup

**Comment by ohwutup** [comment]
Hey @harkmall, I just wanted to double check that you are running from an up-to-date clone of the repo? We fixed a bug a couple of weeks ago that should have fixed this situation. Could you try just running a `git pull origin master` on the repo and trying again?

**Comment by harkmall** [comment]
@ohwutup I followed the instructions in the "Customize" section of the readme if thats what you mean

**Comment by ohwutup** [comment]
Hey @harkmall, sorry for the misunderstanding, maybe a better question is, when was the last time you updated your clone of this repo?

**Comment by harkmall** [comment]
I feel like I'm missing something, I just followed the "Getting Started" section of the readme, I never cloned this repo

**Comment by ohwutup** [comment]
Oh! I'm sorry! Total misunderstanding, I had forgotten about the deploy to heroku button!  My apologies! I will take a look at this shortly and get back to you with a more accurate answer.

**Comment by JohannesDeml** [comment]
Hello everyone!

I got the exact same problem and tried to follow the provided guides:
- I set a config var "FASTLANE_SESSION" with the value I got from spaceauth
- I pulled the latest version as described in the upgrade session of boarding

Config var FASTLANE_SESSION:
`---\n- !ruby/object:HTTP::Cookie\n  name: DES5b1c45f4REMOVED\n  value: HSARMTKNSRVREMOVED=SRVT\n  domain: idmsa.apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 2592000\n  created_at: &1 2016-12-04 18:35:15.446998000 +01:00\n  accessed_at: *1\n- !ruby/object:HTTP::Cookie\n  name: dslang\n  value: US-EN\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: &2 2016-12-04 18:35:15.446434000 +01:00\n  accessed_at: *2\n`

The log I'm getting is this one:
`2016-12-04T17:24:37.101767+00:00 heroku[router]: at=info method=GET path="/" host=REMOVED.herokuapp.com request_id=46558200-e3eb-47c4-a46c-f956d791b526 fwd="141.22.214.224" dyno=web.1 connect=1ms service=944ms status=500 bytes=1669
2016-12-04T17:30:16.698502+00:00 app[web.1]: Started GET "/" for 141.22.214.224 at 2016-12-04 17:30:16 +0000
2016-12-04T17:30:16.699354+00:00 app[web.1]: Processing by InviteController#index as HTML
2016-12-04T17:30:17.453420+00:00 heroku[router]: at=info method=GET path="/" host=REMOVED.herokuapp.com request_id=87a386c5-4455-4ff5-bad0-24235fe67576 fwd="141.22.214.224" dyno=web.1 connect=1ms service=757ms status=500 bytes=1669
2016-12-04T17:30:17.448610+00:00 app[web.1]: Two Factor Authentication for account 'REMOVED' is enabled
2016-12-04T17:30:17.448620+00:00 app[web.1]: If you're running this in a non-interactive session (e.g. server or CI)
2016-12-04T17:30:17.448625+00:00 app[web.1]: check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
2016-12-04T17:30:17.450474+00:00 app[web.1]: Completed 500 Internal Server Error in 751ms
2016-12-04T17:30:17.452484+00:00 app[web.1]: 
2016-12-04T17:30:17.452485+00:00 app[web.1]: NoMethodError (undefined method `ask' for #<Spaceship::TunesClient:0x007ff5f4f1f9b8>):
2016-12-04T17:30:17.452486+00:00 app[web.1]:   app/controllers/invite_controller.rb:163:in `login'
2016-12-04T17:30:17.452486+00:00 app[web.1]:   app/controllers/invite_controller.rb:143:in `app'
2016-12-04T17:30:17.452487+00:00 app[web.1]:   app/controllers/invite_controller.rb:155:in `block in app_metadata'
2016-12-04T17:30:17.452487+00:00 app[web.1]:   app/controllers/invite_controller.rb:153:in `app_metadata'
2016-12-04T17:30:17.452488+00:00 app[web.1]:   app/controllers/invite_controller.rb:168:in `set_app_details'`

Any idea what I'm doing wrong?

**Comment by harkmall** [comment]
@ohwutup Any updates?

**Comment by nprail** [comment]
Is it possible to use an application specific password for this? I couldn't get it to work using the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` password. I has to use `FASTLANE_SESSION` which if I understand correctly, expires eventually. I don't want to have to set that whenever it expires.

**Comment by KrauseFx** [comment]
@nprail no, unfortunately it's not possible to use an application specific password for the generic auth, but only for the iTunes Transporter. There is not much we can do unfortunately.

**Comment by nprail** [comment]
Okay, thanks. It might be a good idea to mention that in the README. It also would be good if the `FASTLANE_SESSION` option was available for the Heroku deploy button so that it's easy to setup.
