### ISSUE TITLE
505 internal server error

### ISSUE THREAD

**Issue by nickpodratz** [fastlane/boarding#121]
The deployment scripts in the Heroku GUI completed, but if I try to open the page for my new app I get the message "We're sorry, but something went wrong. – If you are the application owner check the logs for more information." Here is the log:

```
2017-01-31T09:32:53.414646+00:00 app[web.1]: Completed 500 Internal Server Error in 733ms
2017-01-31T09:32:53.416092+00:00 app[web.1]: 
2017-01-31T09:32:53.416096+00:00 app[web.1]: RuntimeError (Invalid 2 step response {"trustedPhoneNumbers"=>[{"rawNumber"=>"*********97", "numberWithDialCode"=>"+49 •••••••••97", "verifiedDate"=>"11/10/2016 07:30:59 AM", "id"=>1, "verified"=>true, "obfuscatedNumber"=>"•••••••••97", "lastTwoDigits"=>"97", "createDate"=>"10/26/2016 08:25:55 AM", "updateDate"=>"11/10/2016 07:30:59 AM", "countryCode"=>"DE", "countryDialCode"=>"49", "number"=>"*********97", "pushMode"=>"sms", "pending"=>false}], "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false}, "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=<MY_EMAIL>&autoSubmitAccount=true&appId=142", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=<MY_EMAIL>&autoSubmitAccount=true&appId=142", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=<MY_EMAIL>&autoSubmitAccount=true&appId=142", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/?#!repair", "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "managedAccount"=>false, "hsa2Account"=>true, "trustedPhoneNumber"=>{"rawNumber"=>"*********97", "numberWithDialCode"=>"+49 •••••••••97", "verifiedDate"=>"11/10/2016 07:30:59 AM", "id"=>1, "verified"=>true, "obfuscatedNumber"=>"•••••••••97", "lastTwoDigits"=>"97", "createDate"=>"10/26/2016 08:25:55 AM", "updateDate"=>"11/10/2016 07:30:59 AM", "countryCode"=>"DE", "countryDialCode"=>"49", "number"=>"*********97", "pushMode"=>"sms", "pending"=>false}, "supportsRecovery"=>true}):
2017-01-31T09:32:53.416097+00:00 app[web.1]:   app/controllers/invite_controller.rb:164:in `login'
2017-01-31T09:32:53.416097+00:00 app[web.1]:   app/controllers/invite_controller.rb:144:in `app'
2017-01-31T09:32:53.416098+00:00 app[web.1]:   app/controllers/invite_controller.rb:156:in `block in app_metadata'
2017-01-31T09:32:53.416099+00:00 app[web.1]:   app/controllers/invite_controller.rb:154:in `app_metadata'
2017-01-31T09:32:53.416100+00:00 app[web.1]:   app/controllers/invite_controller.rb:169:in `set_app_details'
2017-01-31T09:32:53.416100+00:00 app[web.1]: 
2017-01-31T09:32:53.416101+00:00 app[web.1]: 
2017-01-31T09:32:53.418181+00:00 heroku[router]: at=info method=GET path="/" host=<MY_APP>.herokuapp.com request_id=019d6736-65d3-4946-b6a9-38b2a82537a4 fwd="141.89.216.80" dyno=web.1 connect=0ms service=749ms status=500 bytes=1669
```

I'm not sure what 505: internal server error means. Is it the Heroku service having some issues or is it due to my setup? There were no complaints during setup though.

**Comment by KrauseFx** [comment]
Have you updated to the latest version of boarding, as described in the proejct's readme?

**Comment by nickpodratz** [comment]
Yes, I just checked again. Is this probably related to https://github.com/fastlane/fastlane/issues/4391? I get the confirmation code push message displayed every time I try to open the Heroku app-page and there is no place I can enter it.

**Comment by bastikohn** [comment]
I am having a similar problem:
I get the same error as above, when I don't set FASTLANE_SESSION. However, I don't get the confirmation code via push.
If I set the session with spaceauth I get the following error:

```2017-02-01T16:48:00.238033+00:00 app[web.1]: Processing by InviteController#index as HTML
2017-02-01T16:48:00.261846+00:00 app[web.1]: Make sure to pass the session in a valid format
2017-02-01T16:48:00.261844+00:00 app[web.1]: Error loading session from environment
2017-02-01T16:48:00.262242+00:00 app[web.1]: Completed 500 Internal Server Error in 24ms
2017-02-01T16:48:00.263063+00:00 app[web.1]:
2017-02-01T16:48:00.263064+00:00 app[web.1]: Psych::SyntaxError ((<unknown>): did not find expected '-' indicator while parsing a block collection at line 2 column 1):
2017-02-01T16:48:00.263065+00:00 app[web.1]:   app/controllers/invite_controller.rb:164:in `login'
2017-02-01T16:48:00.263065+00:00 app[web.1]:   app/controllers/invite_controller.rb:144:in `app'
2017-02-01T16:48:00.263067+00:00 app[web.1]:   app/controllers/invite_controller.rb:156:in `block in app_metadata'
2017-02-01T16:48:00.263067+00:00 app[web.1]:   app/controllers/invite_controller.rb:154:in `app_metadata'
2017-02-01T16:48:00.263067+00:00 app[web.1]:   app/controllers/invite_controller.rb:169:in `set_app_details'```

**Comment by mssun** [comment]
Hi, I followed the instruction to deploy boarding in Heroku. I am using two-factor authentication. I just deployed on Heroku and using the latest boarding. After setting the FASTLANE_SESSION environment variable in Heroku's Settings -> Config Variables, I am getting following errors. I don't know it it's related to previous reports. I am sure I copied the right session string from the `fastlane spaceauth -u username` command.

```
2017-02-16T13:21:37.913788+00:00 app[web.1]: Processing by InviteController#index as HTML
2017-02-16T13:21:37.980595+00:00 app[web.1]: Error loading session from environment
2017-02-16T13:21:37.980598+00:00 app[web.1]: Make sure to pass the session in a valid format
2017-02-16T13:21:37.983463+00:00 app[web.1]: Completed 500 Internal Server Error in 67ms
2017-02-16T13:21:37.983818+00:00 app[web.1]: 
2017-02-16T13:21:37.983820+00:00 app[web.1]: ArgumentError (domain is missing):
2017-02-16T13:21:37.983821+00:00 app[web.1]:   app/controllers/invite_controller.rb:164:in `login'
2017-02-16T13:21:37.983821+00:00 app[web.1]:   app/controllers/invite_controller.rb:144:in `app'
2017-02-16T13:21:37.983822+00:00 app[web.1]:   app/controllers/invite_controller.rb:156:in `block in app_metadata'
2017-02-16T13:21:37.983823+00:00 app[web.1]:   app/controllers/invite_controller.rb:154:in `app_metadata'
2017-02-16T13:21:37.983823+00:00 app[web.1]:   app/controllers/invite_controller.rb:169:in `set_app_details'
```

**Comment by marciliojrs** [comment]
Any updates about this issue? I'm having the same problem. I already set the FASTLANE_SESSION env variable in Heroku and everytime I open the heroku app I have this log:

```
2017-04-05T01:47:37.461038+00:00 app[web.1]: Completed 500 Internal Server Error in 635ms
2017-04-05T01:47:37.461990+00:00 app[web.1]:
2017-04-05T01:47:37.461995+00:00 app[web.1]: RuntimeError (Invalid 2 step response
```

**Comment by n8stowell82** [comment]
Yes is there any update to this?  would be nice to be able to use 2fa since any new appleID is forced to have 2fa enabled and cannot be disabled.
