### ISSUE TITLE
Unauthorized Access when getting default_external_group

### ISSUE THREAD

**Issue by Lida** [fastlane/boarding#136]
I get this error fairly consistently when the boarding heroku app has been up for a while. My guess is that the session's authorization has timed out and needs to be refreshed. What would be a good fix for this?

#<Spaceship::Client::UnauthorizedAccessError: Unauthorized Access>
2017-04-26T06:16:18.894462+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/client.rb:624:in `block in send_request'
2017-04-26T06:16:18.894463+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/client.rb:463:in `with_retry'
2017-04-26T06:16:18.894464+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/client.rb:618:in `send_request'
2017-04-26T06:16:18.894465+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/client.rb:507:in `request'
2017-04-26T06:16:18.894465+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/test_flight/client.rb:92:in `get_groups'
2017-04-26T06:16:18.894466+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/test_flight/group.rb:16:in `all'
2017-04-26T06:16:18.894467+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/test_flight/group.rb:30:in `default_external_group'
2017-04-26T06:16:18.894467+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/tunes/application.rb:374:in `default_external_group'
2017-04-26T06:16:18.894468+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:89:in `submit'
2017-04-26T06:16:18.894469+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2017-04-26T06:16:18.894470+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
2017-04-26T06:16:18.894470+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
2017-04-26T06:16:18.894471+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2017-04-26T06:16:18.894472+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
2017-04-26T06:16:18.894472+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
2017-04-26T06:16:18.894473+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2017-04-26T06:16:18.894473+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
2017-04-26T06:16:18.894475+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
2017-04-26T06:16:18.894475+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
2017-04-26T06:16:18.894476+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
2017-04-26T06:16:18.894477+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2017-04-26T06:16:18.894477+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
2017-04-26T06:16:18.894478+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
2017-04-26T06:16:18.894479+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2017-04-26T06:16:18.894480+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
2017-04-26T06:16:18.894481+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2017-04-26T06:16:18.894482+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
2017-04-26T06:16:18.894482+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2017-04-26T06:16:18.894483+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2017-04-26T06:16:18.894484+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
2017-04-26T06:16:18.894484+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
2017-04-26T06:16:18.894485+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
2017-04-26T06:16:18.894486+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2017-04-26T06:16:18.894486+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
2017-04-26T06:16:18.894487+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
2017-04-26T06:16:18.894487+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
2017-04-26T06:16:18.894491+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2017-04-26T06:16:18.894492+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2017-04-26T06:16:18.894493+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
2017-04-26T06:16:18.894493+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
2017-04-26T06:16:18.894494+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
2017-04-26T06:16:18.894495+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
2017-04-26T06:16:18.894512+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
2017-04-26T06:16:18.894513+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:38:in `call'
2017-04-26T06:16:18.894514+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
2017-04-26T06:16:18.894514+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2017-04-26T06:16:18.894515+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
2017-04-26T06:16:18.894516+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
2017-04-26T06:16:18.894516+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
2017-04-26T06:16:18.894517+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2017-04-26T06:16:18.894518+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2017-04-26T06:16:18.894518+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
2017-04-26T06:16:18.894519+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
2017-04-26T06:16:18.894520+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
2017-04-26T06:16:18.894520+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2017-04-26T06:16:18.894521+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2017-04-26T06:16:18.894522+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2017-04-26T06:16:18.894528+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2017-04-26T06:16:18.894529+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2017-04-26T06:16:18.894530+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
2017-04-26T06:16:18.894531+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
2017-04-26T06:16:18.894532+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2017-04-26T06:16:18.894532+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-04-26T06:16:18.894533+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
2017-04-26T06:16:18.894533+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
2017-04-26T06:16:18.894534+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2017-04-26T06:16:18.894534+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
2017-04-26T06:16:18.894535+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
2017-04-26T06:16:18.894536+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2017-04-26T06:16:18.894537+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
2017-04-26T06:16:18.894538+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
2017-04-26T06:16:18.894538+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
2017-04-26T06:16:18.894539+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
2017-04-26T06:16:18.894540+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/configuration.rb:225:in `call'
2017-04-26T06:16:18.894540+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/server.rb:578:in `handle_request'
2017-04-26T06:16:18.894541+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/server.rb:415:in `process_client'
2017-04-26T06:16:18.894546+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/server.rb:275:in `block in run'
2017-04-26T06:16:18.894546+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/thread_pool.rb:116:in `call'
2017-04-26T06:16:18.894547+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.2/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
2017-04-26T06:16:18.895511+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (0.1ms)
2017-04-26T06:16:18.897628+00:00 app[web.1]: Completed 200 OK in 6884ms (Views: 2.8ms)

**Comment by edwardmp** [comment]
@KrauseFx today I noticed a similar issue.

When Spaceship is executed from a web thread, everything works fine. When it is executed from a background thread (sidekiq) this issue starts to happen to 100% of the requests after a certain amount of time. Is there anything we can do about this?

**Comment by joshdholtz** [comment]
@Lida @edwardmp Is this fixed for you if you update to latest boarding and fastlane? This should be fixed for you both now 🙃

**Comment by edwardmp** [comment]
@joshdholtz thanks for reporting back! I no longer use this as I no longer need this use case. Will ask someone else that contacted me about this issue.

By the way, for reference, can you link to the commit that fixed this? I'm also interested in what exactly caused this.

**Comment by joshdholtz** [comment]
I _thhiiiiiinnkkkkkk) its this one - https://github.com/fastlane/fastlane/pull/10826

But I think another spaceship session think was also reworked before this. Lots of things always changing 🙃
