### ISSUE TITLE
App creation fails on heroku when using 2 step verification

### ISSUE THREAD

**Issue by reshadf** [fastlane/boarding#149]
Hi, The app fails deploying because of 2 step verification. I read the README but does this mean I need to clone the boarding project instead of deploying it right away in order to get an app key? Im lost a bit in the docs

**Comment by KrauseFx** [comment]
Hey @reshadf, no, you can directly publish the server on Heroku. You can generate a 2 factor key here https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth

**Comment by reshadf** [comment]
I tried using an app specific password but it says the credentials are invalid.. I am 100% certain they are correct :/

**Comment by KrauseFx** [comment]
App Specific passwords only work for the transporter for binary uploads, not for managing testers. Please use your real user/password and then generate the session token using `spaceauth`

**Comment by reshadf** [comment]
Where do I put that key in heroku while using the heroku installer on the github page?

**Comment by KrauseFx** [comment]
You can set that on Heroku.com when you access your app's environment variables 👍

**Comment by reshadf** [comment]
I have tried setting the variable FASTLANE_SESSION but it seems like its ignored, all the other variables work just fine. (ITC_USER etc .. ) It keeps asking for a way to verify through 2 step verification Is that the correct key to use? *FASTLANE_SESSION* ?

**Comment by beyerss** [comment]
@KrauseFx - I don't have an option to set the application's environment variable for `FASTLANE_SESSION` because the application creation fails due to 2 factor auth. Below is the screen shot of the only settings I have to choose from because I can't get beyond the "New App" screen on Heroku.

<img width="1122" alt="screen shot 2017-05-23 at 1 52 42 pm" src="https://cloud.githubusercontent.com/assets/1074621/26368259/262812e4-3fbf-11e7-9f6d-6576ec135efb.png">

Here are my error logs:

> rake aborted!
       Spaceship::Client::UnauthorizedAccessError: Unauthorized Access
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:627:in `block in send_request'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:466:in `with_retry'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:621:in `send_request'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:510:in `request'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:410:in `send_shared_login_request'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/tunes/tunes_client.rb:161:in `send_login_request'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:588:in `do_login'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:346:in `login'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:119:in `login'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/tunes/spaceship.rb:22:in `login'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/app/services/boarding_service.rb:139:in `ensure_values'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/app/services/boarding_service.rb:35:in `initialize'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/config/initializers/services.rb:1:in `new'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/config/initializers/services.rb:1:in `<top (required)>'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/config/environment.rb:5:in `<top (required)>'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build_5fe3ccc3e916375bb284848678b04799/fastlane-boarding-80201eb/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by reshadf** [comment]
@beyerss I eventually created a new Apple ID just for this. It wouldn't work with 2 step verification. I even tried cloning Boarding and create a rails application on heroku, add config variables and then deploy but new errors were coming up all the time all related to verification. I think the best solution would be to create a new Apple ID to do stuff like this on.

**Comment by JigneshPatel23** [comment]
Similar issue I am facing even I have set up in a local machine it works with login but no luck with the session.

**Comment by JohannesDeml** [comment]
I think handling the two factor authentication in a more streamlined way would be interesting, since Apple seems to enforce two factor more and more. I was stuck the whole morning to get it working again. Actually adding the session token worked for me in the end, but it was a long journey to get there. And the session expiring every month is not too smooth. Is there a way to generate a persistent token (You can set tust computer in the web interface to always trust that device if I'm correct).

Maybe an additional field for the deployment script would be a good first move, but a more persistent solution would be great in the long run.
