### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by 1hakr** [fastlane/boarding#186]
When a new user is signing up i'm getting this message. I have no clue whats happening. Please need some help here.

`Something went wrong, please contact the application owner: <?xml version="1.0" encoding="UTF-8"?> <String>There is no route for the path 'users/pre/int'.</String>`

Log:
```
2017-11-16T03:49:42.133746+00:00 app[web.1]: Started POST "/submit" for 117.201.216.226 at 2017-11-16 03:49:42 +0000
2017-11-16T03:49:42.139364+00:00 app[web.1]: Processing by InviteController#submit as HTML
2017-11-16T03:49:42.139477+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxxxx", "first_name"=>"Hari", "last_name"=>"Dulipudi", "email"=>"hakr@dworks.in"}
2017-11-16T03:49:42.159883+00:00 app[web.1]: Creating a new tester: hakr@dworks.in - Hari Dulipudi
2017-11-16T03:49:43.462307+00:00 app[web.1]: #<Spaceship::Client::UnexpectedResponse: <?xml version="1.0" encoding="UTF-8"?>
2017-11-16T03:49:43.462318+00:00 app[web.1]: <String>There is no route for the path 'users/pre/int'.</String>
2017-11-16T03:49:43.462319+00:00 app[web.1]: >
2017-11-16T03:49:43.462926+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/client.rb:588:in `parse_response'
2017-11-16T03:49:43.462928+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/tunes/tunes_client.rb:1088:in `testers'
2017-11-16T03:49:43.462929+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/tunes/tester.rb:79:in `all'
2017-11-16T03:49:43.462930+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/tunes/tester.rb:86:in `find'
2017-11-16T03:49:43.462931+00:00 app[web.1]: /app/app/services/boarding_service.rb:114:in `find_app_tester'
2017-11-16T03:49:43.462931+00:00 app[web.1]: /app/app/services/boarding_service.rb:44:in `add_tester'
2017-11-16T03:49:43.462932+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:92:in `create_and_add_tester'
2017-11-16T03:49:43.462933+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:75:in `submit'
```

**Comment by boxenjim** [comment]
I'm getting the same error, the path its saying has no route is different for me though

**Comment by 1hakr** [comment]
Looks like spaceship is not able to handle the response coz it might have changed @KrauseFx @taquitos ?

**Comment by ohayon** [comment]
Hi folks, we are currently working on a fix for these issues, you can see some more info here: https://github.com/fastlane/boarding/issues/185 and there is a PR in progress here: https://github.com/fastlane/fastlane/pull/10921

**Comment by linked67** [comment]
How to update heroku to use the latest fix ?

**Comment by 1hakr** [comment]
It's a dependency service which will work only after fastlane is released.

**Comment by raudabaugh** [comment]
@linked67 @1hakr You can edit the dependency in `Gemfile` to use the fix:

`gem 'fastlane', :git => 'https://github.com/fastlane/fastlane.git', :branch => 'master'`

**Comment by raudabaugh** [comment]
I'm getting the same error after deploying with https://github.com/fastlane/fastlane/pull/10921 merged. It looks like there may still be references to old endpoints, such as in https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tester.rb

**Comment by linked67** [comment]
I have try this yesterday but the Gemfile stick to the latest version number which don't include the fix (i think).

When you check https://github.com/fastlane/fastlane/releases, 2.64.1 is 7 days old now and don't include the fix we need.

**Comment by taquitos** [comment]
We just made a release to fix some of these issues. We'll be continuing to roll out fixes as we make them. For the latest, you can always point to master 🎉

**Comment by 1hakr** [comment]
@taquitos thanks for the update. I have updated to latest release but still its not working. Hope to see all the fixes soon

**Comment by pcsanwald** [comment]
I've also updated to the latest release, and am still seeing the error. If there's anything I can do to help with testing, happy to do it! thanks for your quick work on this.

**Comment by linked67** [comment]
It's fine from my side on a new install

**Comment by pcsanwald** [comment]
on a new install pointing to `master`, I get a crash with `fastlane pilot add \"MY_EMAIL@gmail.com\" -a $FASTLANE_APP_IDENTIFIER --username $FASTLANE_ITUNES_CONNECT_USERNAME --first_name \"Paul\" --last_name \"Sanwald\"`

The crash gives me:

```
{
	"eventTime": "2017-11-20T22:05:58+00:00",
	"serviceContext": {
		"service": "fastlane",
		"version": "2.65.0"
	},
	"message": "[USER_ERROR]: [fastlane_path]/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'\n[fastlane_path]/pilot/lib/pilot/commands_generator.rb:95:in `block (2 levels) in run'\n[gem_home]/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'\n[gem_home]/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'\n[gem_home]/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'\n[fastlane_path]/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'\n[gem_home]/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'\n[fastlane_path]/pilot/lib/pilot/commands_generator.rb:159:in `run'\n[fastlane_path]/pilot/lib/pilot/commands_generator.rb:12:in `start'\n[fastlane_path]/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'\n[fastlane_path]/bin/fastlane:20:in `<top (required)>'\n~/vendor/bundle/bin/fastlane:17:in `load'\n~/vendor/bundle/bin/fastlane:17:in `<main>'"
}
```

**Comment by taquitos** [comment]
`fastlane pilot add` doesn't work just yet... almost there. You can follow along on this _fastlane_  issue: https://github.com/fastlane/fastlane/issues/10930

**Comment by gcox** [comment]
As of 2.66, the error has changed to: `uninitialized constant Spaceship::Tunes::Tester`

**Comment by ohayon** [comment]
Hey @gcox - could you provide the stack trace? 🚀

**Comment by taquitos** [comment]
This is the same root cause as: https://github.com/fastlane/fastlane/issues/10930
which I just fixed in: https://github.com/fastlane/boarding/pull/193 🎈

**Comment by 1hakr** [comment]
i just tried with a new application and its working now
