### ISSUE TITLE
 undefined method `admin?' for nil:NilClass

### ISSUE THREAD

**Issue by lianleven** [fastlane/boarding#200]
Application test error

**Comment by taquitos** [comment]
Hey @lianleven could you post the log output? That should help us track down where this is coming from and what we can do to fix it 👍

**Comment by lianleven** [comment]
Hello @taquitos  I forgot to keep the output log. I use the iTunes connect account, legal and management of the account is a failure, the error such as title. ITunes connect re-add an account set for the management is successful.

**Comment by padupuy** [comment]
Hello there, to reproduce the bug : 
- deploy an app to heroku via https://www.heroku.com/deploy?template=https://github.com/fastlane/boarding
- try to connect to the beta dashboard
- failed to connect

Here are the logs 

```sh
2018-08-07T09:41:08.891391+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:438:in `process_client'
2018-08-07T09:41:08.891392+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:302:in `block in run'
2018-08-07T09:41:08.892289+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (0.3ms)
2018-08-07T09:41:08.896403+00:00 heroku[router]: at=info method=POST path="/submit" host=pax-boarding.herokuapp.com request_id=10932b5b-f271-4612-bed2-cb9b06ca750e fwd="92.154.34.9" dyno=web.1 connect=1ms service=299ms status=200 bytes=2375 protocol=https
2018-08-07T09:42:55.112963+00:00 app[web.1]: Started POST "/submit" for 92.154.34.9 at 2018-08-07 09:42:55 +0000
2018-08-07T09:42:55.113700+00:00 app[web.1]: Processing by InviteController#submit as HTML
2018-08-07T09:42:55.113742+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"5JG4sNDXTtTdfF2m6LCGeCirRXsjylcz/wuVrT96YTbT+6R4y4ql19IfQ1dAcsUwWG5bmRvGHFyeAZYNcH64Zw==", "first_name"=>"Pax", "last_name"=>"Pix", "email"=>"pax@gmail.com", "token"=>"pax"}
2018-08-07T09:42:55.114260+00:00 app[web.1]: Creating a new tester: pax@gmail.com - Pax Pix
2018-08-07T09:42:55.514577+00:00 heroku[router]: at=info method=GET path="/assets/application-f02991750523a36c5cc72d314f2cc2b25881facb537feebbe1c4ae44eeb5b641.js" host=pax-boarding.herokuapp.com request_id=4c08df7f-3a91-4375-a90a-cd62e01bea5e fwd="92.154.34.9" dyno=web.1 connect=0ms service=1ms status=304 bytes=48 protocol=https
2018-08-07T09:42:55.488534+00:00 heroku[router]: at=info method=GET path="/assets/application-f60234b773e4108bf3a23e1803575b1537cdb89e41b5d54103ab4442d9173afc.css" host=pax-boarding.herokuapp.com request_id=e2f14cbd-c713-49ed-b137-50fb40420668 fwd="92.154.34.9" dyno=web.1 connect=0ms service=1ms status=304 bytes=48 protocol=https
2018-08-07T09:42:55.448272+00:00 heroku[router]: at=info method=POST path="/submit" host=pax-boarding.herokuapp.com request_id=bf64d7c6-c2b6-4b71-bcbb-98bb547d2c1d fwd="92.154.34.9" dyno=web.1 connect=0ms service=338ms status=200 bytes=2375 protocol=https
2018-08-07T09:42:55.445987+00:00 app[web.1]: #<NoMethodError: undefined method `admin?' for nil:NilClass>
2018-08-07T09:42:55.446189+00:00 app[web.1]: /app/app/services/boarding_service.rb:102:in `find_app_tester'
2018-08-07T09:42:55.446191+00:00 app[web.1]: /app/app/services/boarding_service.rb:44:in `add_tester'
2018-08-07T09:42:55.446193+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:92:in `create_and_add_tester'
2018-08-07T09:42:55.446194+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:75:in `submit'
2018-08-07T09:42:55.446198+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2018-08-07T09:42:55.446200+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:198:in `process_action'
2018-08-07T09:42:55.446201+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:10:in `process_action'
2018-08-07T09:42:55.446202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2018-08-07T09:42:55.446203+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
2018-08-07T09:42:55.446204+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2018-08-07T09:42:55.446206+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
2018-08-07T09:42:55.446207+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
2018-08-07T09:42:55.446208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
2018-08-07T09:42:55.446210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
2018-08-07T09:42:55.446211+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:19:in `process_action'
2018-08-07T09:42:55.446212+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/rescue.rb:29:in `process_action'
2018-08-07T09:42:55.446215+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2018-08-07T09:42:55.446216+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `block in instrument'
2018-08-07T09:42:55.446217+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2018-08-07T09:42:55.446219+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `instrument'
2018-08-07T09:42:55.446220+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2018-08-07T09:42:55.446221+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2018-08-07T09:42:55.446223+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:137:in `process'
2018-08-07T09:42:55.446224+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:30:in `process'
2018-08-07T09:42:55.446225+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:196:in `dispatch'
2018-08-07T09:42:55.446227+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2018-08-07T09:42:55.446228+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:237:in `block in action'
2018-08-07T09:42:55.446229+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
2018-08-07T09:42:55.446230+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2018-08-07T09:42:55.446232+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2018-08-07T09:42:55.446233+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `each'
2018-08-07T09:42:55.446234+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `serve'
2018-08-07T09:42:55.446235+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:817:in `call'
2018-08-07T09:42:55.446237+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
2018-08-07T09:42:55.446238+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/etag.rb:24:in `call'
2018-08-07T09:42:55.446240+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/conditionalget.rb:38:in `call'
2018-08-07T09:42:55.446241+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/head.rb:13:in `call'
2018-08-07T09:42:55.446242+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2018-08-07T09:42:55.446250+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/flash.rb:260:in `call'
2018-08-07T09:42:55.446252+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/session/abstract/id.rb:225:in `context'
2018-08-07T09:42:55.446253+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/session/abstract/id.rb:220:in `call'
2018-08-07T09:42:55.446254+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2018-08-07T09:42:55.446256+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2018-08-07T09:42:55.446257+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
2018-08-07T09:42:55.446258+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
2018-08-07T09:42:55.446260+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
2018-08-07T09:42:55.446261+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2018-08-07T09:42:55.446262+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2018-08-07T09:42:55.446263+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2018-08-07T09:42:55.446265+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2018-08-07T09:42:55.446266+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
2018-08-07T09:42:55.446267+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
2018-08-07T09:42:55.446269+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2018-08-07T09:42:55.446270+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
2018-08-07T09:42:55.446271+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
2018-08-07T09:42:55.446273+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
2018-08-07T09:42:55.446274+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2018-08-07T09:42:55.446275+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/methodoverride.rb:22:in `call'
2018-08-07T09:42:55.446277+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/runtime.rb:18:in `call'
2018-08-07T09:42:55.446278+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2018-08-07T09:42:55.446279+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/static.rb:120:in `call'
2018-08-07T09:42:55.446281+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/sendfile.rb:113:in `call'
2018-08-07T09:42:55.446282+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
2018-08-07T09:42:55.446283+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
2018-08-07T09:42:55.446285+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/configuration.rb:225:in `call'
2018-08-07T09:42:55.446286+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:624:in `handle_request'
2018-08-07T09:42:55.446287+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:438:in `process_client'
2018-08-07T09:42:55.446288+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:302:in `block in run'
2018-08-07T09:42:55.446290+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.3/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2018-08-07T09:42:55.447368+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (0.4ms)
2018-08-07T09:42:55.449060+00:00 app[web.1]: Completed 200 OK in 335ms (Views: 2.6ms)
```

**Comment by chadyj** [comment]
I had the exact same issue! https://github.com/fastlane/boarding/issues/156#issuecomment-357836019

**Comment by varshneydevansh** [comment]
is this still pending?

**Comment by rogerluan** [comment]
No idea @varshneydevansh but I can say the boarding project hasn't been kept "maintained" for a long time 😞
