### ISSUE TITLE
new heroku deployments immediately crashing

### ISSUE THREAD

**Issue by 33b5e5** [fastlane/boarding#212]
```
2018-03-29T21:46:54.268168+00:00 heroku[worker.1]: Starting process with command `bundle exec rake jobs:work`
2018-03-29T21:46:54.912391+00:00 heroku[worker.1]: State changed from starting to up
2018-03-29T21:46:58.266227+00:00 heroku[worker.1]: Process exited with status 1
2018-03-29T21:46:58.282547+00:00 heroku[worker.1]: State changed from up to crashed
2018-03-29T21:46:58.113664+00:00 app[worker.1]: rake aborted!
2018-03-29T21:46:58.113708+00:00 app[worker.1]: Don't know how to build task 'jobs:work' (see --tasks)
2018-03-29T21:46:58.114187+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
2018-03-29T21:46:58.114189+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
2018-03-29T21:46:58.114191+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
2018-03-29T21:46:58.114193+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
2018-03-29T21:46:58.114195+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
2018-03-29T21:46:58.114197+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2018-03-29T21:46:58.114215+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2018-03-29T21:46:58.114217+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
2018-03-29T21:46:58.114218+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
2018-03-29T21:46:58.114220+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
2018-03-29T21:46:58.114221+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
2018-03-29T21:46:58.114223+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
2018-03-29T21:46:58.114225+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
2018-03-29T21:46:58.114226+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
2018-03-29T21:46:58.114228+00:00 app[worker.1]: /app/bin/bundle:3:in `load'
2018-03-29T21:46:58.114229+00:00 app[worker.1]: /app/bin/bundle:3:in `<main>'
2018-03-29T21:46:58.114235+00:00 app[worker.1]: (See full trace by running task with --trace)
```

I've tried deploying twice with the same results. I'm not sure what other information is helpful, so please let me know what else I can provide. I was able to deploy to Azure successfully using the same underlying app and iTC access.

**Comment by 33b5e5** [comment]
Some additional output from the Heroku logs:

```
2018-03-29T21:59:28.893242+00:00 heroku[web.1]: State changed from starting to crashed
2018-03-29T21:59:28.896198+00:00 heroku[web.1]: State changed from crashed to starting
2018-03-29T21:59:28.852099+00:00 heroku[web.1]: Process exited with status 1
2018-03-29T21:59:35.528372+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2018-03-29T21:59:38.573305+00:00 heroku[web.1]: State changed from starting to crashed
2018-03-29T21:59:38.555734+00:00 heroku[web.1]: Process exited with status 1
2018-03-29T21:59:38.328166+00:00 app[web.1]: [4] Puma starting in cluster mode...
2018-03-29T21:59:38.328192+00:00 app[web.1]: [4] * Version 3.11.3 (ruby 2.3.4-p301), codename: Love Song
2018-03-29T21:59:38.328194+00:00 app[web.1]: [4] * Min threads: 5, max threads: 5
2018-03-29T21:59:38.328200+00:00 app[web.1]: [4] * Environment: production
2018-03-29T21:59:38.328202+00:00 app[web.1]: [4] * Process workers: 2
2018-03-29T21:59:38.328206+00:00 app[web.1]: [4] * Preloading application
2018-03-29T21:59:38.360081+00:00 app[web.1]: [4] ! Unable to load application: NameError: uninitialized constant Rails
2018-03-29T21:59:38.360228+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.3.0/bin/puma)
2018-03-29T21:59:38.360324+00:00 app[web.1]: NameError: uninitialized constant Rails
2018-03-29T21:59:38.360327+00:00 app[web.1]:   /app/config/environment.rb:2:in `<top (required)>'
2018-03-29T21:59:38.360329+00:00 app[web.1]:   config.ru:3:in `require'
2018-03-29T21:59:38.360331+00:00 app[web.1]:   config.ru:3:in `block in <main>'
2018-03-29T21:59:38.360333+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:55:in `instance_eval'
2018-03-29T21:59:38.360334+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:55:in `initialize'
2018-03-29T21:59:38.360336+00:00 app[web.1]:   config.ru:in `new'
2018-03-29T21:59:38.360337+00:00 app[web.1]:   config.ru:in `<main>'
2018-03-29T21:59:38.360339+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:49:in `eval'
2018-03-29T21:59:38.360341+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:49:in `new_from_string'
2018-03-29T21:59:38.360342+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:40:in `parse_file'
2018-03-29T21:59:38.360344+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/configuration.rb:318:in `load_rackup'
2018-03-29T21:59:38.360345+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/configuration.rb:243:in `app'
2018-03-29T21:59:38.360347+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/runner.rb:138:in `load_and_bind'
2018-03-29T21:59:38.360349+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/cluster.rb:397:in `run'
2018-03-29T21:59:38.360350+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/launcher.rb:183:in `run'
2018-03-29T21:59:38.360352+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/cli.rb:77:in `run'
2018-03-29T21:59:38.360354+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/bin/puma:10:in `<top (required)>'
2018-03-29T21:59:38.360355+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:22:in `load'
2018-03-29T21:59:38.360357+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:22:in `<top (required)>'
```

**Comment by joshdholtz** [comment]
@33b5e5 Hey! It looks like your "worker dyno" is **on** but your "web dyno" is **off**. Can you make sure your heroic dashboard looks like the following image?

The web dyno should be the only one that is on 

<img width="631" alt="screen shot 2018-03-29 at 4 59 41 pm" src="https://user-images.githubusercontent.com/401294/38115740-b227c922-3372-11e8-8e6c-bf481597ce6d.png">

**Comment by 33b5e5** [comment]
Thanks for the response @joshdholtz. I admittedly was fiddling with the dyno settings while trying to troubleshoot, but setting them back to the defaults as pictured and restarting the dynos results in the same error. I also tried deploying to a new app and not fiddling with the Heroku settings, but it's the same.

![screen shot 2018-03-29 at 3 03 17 pm](https://user-images.githubusercontent.com/2781306/38115910-b819764c-3362-11e8-9eff-23c96b61ea68.png)

```
2018-03-29T22:03:48.098517+00:00 heroku[web.1]: State changed from crashed to starting
2018-03-29T22:03:54.533177+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2018-03-29T22:03:57.656382+00:00 heroku[web.1]: Process exited with status 1
2018-03-29T22:03:57.682564+00:00 heroku[web.1]: State changed from starting to crashed
2018-03-29T22:03:57.394545+00:00 app[web.1]: [4] Puma starting in cluster mode...
2018-03-29T22:03:57.394565+00:00 app[web.1]: [4] * Version 3.11.3 (ruby 2.3.4-p301), codename: Love Song
2018-03-29T22:03:57.394567+00:00 app[web.1]: [4] * Min threads: 5, max threads: 5
2018-03-29T22:03:57.394569+00:00 app[web.1]: [4] * Environment: production
2018-03-29T22:03:57.394572+00:00 app[web.1]: [4] * Process workers: 2
2018-03-29T22:03:57.394696+00:00 app[web.1]: [4] * Preloading application
2018-03-29T22:03:57.429751+00:00 app[web.1]: [4] ! Unable to load application: NameError: uninitialized constant Rails
2018-03-29T22:03:57.429979+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.3.0/bin/puma)
2018-03-29T22:03:57.430125+00:00 app[web.1]: NameError: uninitialized constant Rails
2018-03-29T22:03:57.430128+00:00 app[web.1]:   /app/config/environment.rb:2:in `<top (required)>'
2018-03-29T22:03:57.430130+00:00 app[web.1]:   config.ru:3:in `require'
2018-03-29T22:03:57.430132+00:00 app[web.1]:   config.ru:3:in `block in <main>'
2018-03-29T22:03:57.430134+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:55:in `instance_eval'
2018-03-29T22:03:57.430135+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:55:in `initialize'
2018-03-29T22:03:57.430137+00:00 app[web.1]:   config.ru:in `new'
2018-03-29T22:03:57.430139+00:00 app[web.1]:   config.ru:in `<main>'
2018-03-29T22:03:57.430140+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:49:in `eval'
2018-03-29T22:03:57.430142+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:49:in `new_from_string'
2018-03-29T22:03:57.430143+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:40:in `parse_file'
2018-03-29T22:03:57.430145+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/configuration.rb:318:in `load_rackup'
2018-03-29T22:03:57.430147+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/configuration.rb:243:in `app'
2018-03-29T22:03:57.430149+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/runner.rb:138:in `load_and_bind'
2018-03-29T22:03:57.430151+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/cluster.rb:397:in `run'
2018-03-29T22:03:57.430152+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/launcher.rb:183:in `run'
2018-03-29T22:03:57.430154+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/lib/puma/cli.rb:77:in `run'
2018-03-29T22:03:57.430156+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.3/bin/puma:10:in `<top (required)>'
2018-03-29T22:03:57.430158+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:22:in `load'
2018-03-29T22:03:57.430181+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:22:in `<top (required)>'
```

**Comment by joshdholtz** [comment]
This is _very_ strange 🤔 I literally created a new app from the Heroku button on the README about 15 minutes before you posted your issue. Did you deploy with the Heroku button?

**Comment by 33b5e5** [comment]
> Did you deploy with the Heroku button?

Yep!

**Comment by joshdholtz** [comment]
What environment variables did you all fill out when that form popped up? I only filled out user, password, and app id 🤔

**Comment by 33b5e5** [comment]
ITC_USER, ITC_PASSWORD, ITC_APP_ID, ITC_APP_TESTER_GROUPS. So it looks like adding the tester group is the only difference.

**Comment by 33b5e5** [comment]
I tried removing ITC_APP_TESTER_GROUPS from the Heroku settings, then restarted all dynos, but no change.

I'm tempted to try the "Update to a new version" (https://github.com/fastlane/boarding#recommended-using-the-terminal) steps just to see if it un-wedges anything.

**Comment by joshdholtz** [comment]
Does your `ITC_PASSWORD` have any "strange" characters in it maybe? Or does your `ITC_APP_TESTER_GROUPS` have any strange character in it?

**Comment by joshdholtz** [comment]
@33b5e5 I _think_ I know the issue. Let me push a change real quickly 😊

**Comment by joshdholtz** [comment]
@33b5e5 I just merged #213. Can you try to create it from scratch ONE more time 😊

**Comment by 33b5e5** [comment]
It's working fine now. Thank you very much!

**Comment by joshdholtz** [comment]
@33b5e5 Woot! Happy fastlaning 🚀
