### ISSUE TITLE
App crashes on Heroku

### ISSUE THREAD

**Issue by dbltnk** [fastlane/boarding#218]
Boarding worked for me on Heroku for a couple months. Today I discovered that it's now broken - without me making any changes to it. This is what Heroku says:

> Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

This is the log I get - restarted the app on Heroku right before that (to no availal):
`2018-06-02T13:09:53.226862+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/configuration.rb:243:in `app'
2018-06-02T13:09:53.226863+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/runner.rb:138:in `load_and_bind'
2018-06-02T13:09:53.226864+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/cluster.rb:397:in `run'
2018-06-02T13:09:53.226866+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/launcher.rb:183:in `run'
2018-06-02T13:09:53.226867+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/lib/puma/cli.rb:77:in `run'
2018-06-02T13:09:53.226874+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.11.2/bin/puma:10:in `<top (required)>'
2018-06-02T13:09:53.226875+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:22:in `load'
2018-06-02T13:09:53.226877+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:22:in `<top (required)>'
2018-06-02T14:04:40.500198+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=push-testflight-signup.herokuapp.com request_id=e50e9377-bb8f-4ef9-aca1-610ce8d80e2f fwd="95.90.196.108" dyno= connect= service= status=503 bytes= protocol=https
2018-06-02T14:04:40.883461+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=push-testflight-signup.herokuapp.com request_id=e56d4b4c-d8b4-4f29-9241-ff2a4b170a9c fwd="95.90.196.108" dyno= connect= service= status=503 bytes= protocol=https`

Tried to deploy a clean build to Heroku but I get the same issue as described here: https://github.com/fastlane/boarding/issues/217

**Comment by Thwaitesy** [comment]
See #217 

Related to https://github.com/fastlane/fastlane/issues/12577

**Comment by dbltnk** [comment]
Thank you, @Thwaitesy. Clicking continue on the popup after logging in with the build account fixed the issue.
