### ISSUE TITLE
403 from iTunes when accessing /testers

### ISSUE THREAD

**Issue by suculent** [fastlane/boarding#228]
Started happening yesterday after the Keynote:

Problem accessing /v2/providers/891960/apps/1386652007/testers

```
Sep 13 02:16:20 tf-landing app/web.1: #<Spaceship::UnexpectedResponse: <html> 
Sep 13 02:16:20 tf-landing app/web.1: <head> 
Sep 13 02:16:20 tf-landing app/web.1: <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/> 
Sep 13 02:16:20 tf-landing app/web.1: <title>Error 403 </title> 
Sep 13 02:16:20 tf-landing app/web.1: </head> 
Sep 13 02:16:20 tf-landing app/web.1: <body> 
Sep 13 02:16:20 tf-landing app/web.1: <h2>HTTP ERROR: 403</h2> 
Sep 13 02:16:20 tf-landing app/web.1: <p>Problem accessing /v2/providers/891960/apps/1386652007/testers. Reason: 
Sep 13 02:16:20 tf-landing app/web.1: <pre>    Forbidden</pre></p> 
Sep 13 02:16:20 tf-landing app/web.1: <hr /><i><small>Powered by Jetty://</small></i> 
Sep 13 02:16:20 tf-landing app/web.1: </body> 
Sep 13 02:16:20 tf-landing app/web.1: </html> 
Sep 13 02:16:20 tf-landing app/web.1: > 
Sep 13 02:16:20 tf-landing app/web.1: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.86.2/spaceship/lib/spaceship/test_flight/client.rb:289:in `handle_response' 
Sep 13 02:16:20 tf-landing app/web.1: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.86.2/spaceship/lib/spaceship/test_flight/client.rb:203:in `search_for_tester_in_app' 
Sep 13 02:16:20 tf-landing app/web.1: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.86.2/spaceship/lib/spaceship/test_flight/tester.rb:100:in `search' 
Sep 13 02:16:20 tf-landing app/web.1: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.86.2/spaceship/lib/spaceship/test_flight/tester.rb:87:in `find' 
Sep 13 02:16:20 tf-landing app/web.1: /app/app/services/boarding_service.rb:106:in `find_app_tester' 
Sep 13 02:16:20 tf-landing app/web.1: /app/app/services/boarding_service.rb:44:in `add_tester' 
Sep 13 02:16:20 tf-landing app/web.1: /app/app/controllers/invite_controller.rb:92:in `create_and_add_tester' 
Sep 13 02:16:20 tf-landing app/web.1: /app/app/controllers/invite_controller.rb:75:in `submit' 
```

**Comment by RishabhTayal** [comment]
Getting the same error.

**Comment by suculent** [comment]
Fixed by updating Fastlane dependency to latest version. See  https://github.com/fastlane/boarding/pull/229
