### ISSUE TITLE
Vanilla deployment to Heroku fails

### ISSUE THREAD

**Issue by marbetschar** [fastlane/boarding#250]
A Vanilla-fresh deployment to Heroku fails with the following message - any ideas how to fix this? FWIW: I just clicked on "Deploy to Heroku" on GitHub master branch.

```
...
-----> Detecting rake tasks

 !

 !     Could not detect rake tasks

 !     ensure you can run `$ bundle exec rake -P` against your app

 !     and using the production group of your Gemfile.

 !     Activating bundler (2.0.1) failed:

 !     Could not find 'bundler' (2.0.1) required by your /tmp/build_450b956d8551277fbb2279458df16de6/Gemfile.lock.

 !     To update to the latest version installed on your system, run `bundle update --bundler`.

 !     To install the missing version, run `gem install bundler:2.0.1`

 !     Checked in 'GEM_PATH=vendor/bundle/ruby/2.5.0', execute `gem env` for more information
...
```

**Full Heroku Output:**

```
-----> Ruby app detected

-----> Compiling Ruby/Rails

-----> Using Ruby version: ruby-2.5.5

-----> Installing dependencies using bundler 2.0.2

       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment

       Fetching gem metadata from https://rubygems.org/........

       Fetching rake 12.3.2

       Installing rake 12.3.2

       Fetching CFPropertyList 3.0.0

       Fetching concurrent-ruby 1.1.5

       Fetching minitest 5.11.3

       Installing CFPropertyList 3.0.0

       Installing minitest 5.11.3

       Fetching thread_safe 0.3.6

       Installing concurrent-ruby 1.1.5

       Installing thread_safe 0.3.6

       Fetching builder 3.2.3

       Installing builder 3.2.3

       Fetching erubis 2.7.0

       Installing erubis 2.7.0

       Fetching mini_portile2 2.4.0

       Installing mini_portile2 2.4.0

       Fetching crass 1.0.4

       Installing crass 1.0.4

       Fetching rack 2.0.7

       Installing rack 2.0.7

       Fetching nio4r 2.3.1

       Installing nio4r 2.3.1 with native extensions

       Fetching websocket-extensions 0.1.3

       Installing websocket-extensions 0.1.3

       Fetching mini_mime 1.0.1

       Installing mini_mime 1.0.1

       Fetching arel 7.1.4

       Fetching public_suffix 2.0.5

       Installing arel 7.1.4

       Installing public_suffix 2.0.5

       Fetching atomos 0.1.3

       Installing atomos 0.1.3

       Fetching execjs 2.7.0

       Installing execjs 2.7.0

       Fetching babosa 1.0.2

       Installing babosa 1.0.2

       Fetching ffi 1.10.0

       Using bundler 2.0.2

       Fetching claide 1.0.2

       Installing claide 1.0.2

       Installing ffi 1.10.0 with native extensions

       Fetching coffee-script-source 1.12.2

       Installing coffee-script-source 1.12.2

       Fetching method_source 0.9.2

       Installing method_source 0.9.2

       Fetching thor 0.20.3

       Installing thor 0.20.3

       Fetching colored 1.2

       Installing colored 1.2

       Fetching colored2 3.1.2

       Installing colored2 3.1.2

       Fetching highline 1.7.10

       Installing highline 1.7.10

       Fetching declarative 0.0.10

       Installing declarative 0.0.10

       Fetching declarative-option 0.1.0

       Installing declarative-option 0.1.0

       Fetching digest-crc 0.4.1

       Installing digest-crc 0.4.1

       Fetching unf_ext 0.0.7.6

       Installing unf_ext 0.0.7.6 with native extensions

       Fetching dotenv 2.7.2

       Installing dotenv 2.7.2

       Fetching emoji_regex 1.0.1

       Installing emoji_regex 1.0.1

       Fetching excon 0.64.0

       Installing excon 0.64.0

       Fetching multipart-post 2.0.0

       Installing multipart-post 2.0.0

       Fetching fastimage 2.1.5

       Installing fastimage 2.1.5

       Fetching gh_inspector 1.1.3

       Installing gh_inspector 1.1.3

       Fetching jwt 2.1.0

       Installing jwt 2.1.0

       Fetching memoist 0.16.0

       Installing memoist 0.16.0

       Fetching multi_json 1.13.1

       Installing multi_json 1.13.1

       Fetching os 1.0.1

       Installing os 1.0.1

       Fetching httpclient 2.8.3

       Installing httpclient 2.8.3

       Fetching mime-types-data 3.2019.0331

       Installing mime-types-data 3.2019.0331

       Fetching uber 0.1.0

       Installing uber 0.1.0

       Fetching retriable 3.1.2

       Installing retriable 3.1.2

       Fetching json 2.2.0

       Installing json 2.2.0 with native extensions

       Fetching mini_magick 4.5.1

       Installing mini_magick 4.5.1

       Fetching multi_xml 0.6.0

       Installing multi_xml 0.6.0

       Fetching plist 3.5.0

       Installing plist 3.5.0

       Fetching rubyzip 1.2.3

       Installing rubyzip 1.2.3

       Fetching security 0.1.3

       Installing security 0.1.3

       Fetching naturally 2.2.0

       Installing naturally 2.2.0

       Fetching slack-notifier 2.3.2

       Installing slack-notifier 2.3.2

       Fetching terminal-notifier 2.0.0

       Installing terminal-notifier 2.0.0

       Fetching unicode-display_width 1.6.0

       Installing unicode-display_width 1.6.0

       Fetching tty-screen 0.7.0

       Installing tty-screen 0.7.0

       Fetching tty-cursor 0.7.0

       Installing tty-cursor 0.7.0

       Fetching word_wrap 1.0.0

       Installing word_wrap 1.0.0

       Fetching nanaimo 0.2.6

       Installing nanaimo 0.2.6

       Fetching rouge 2.0.7

       Installing rouge 2.0.7

       Fetching http_accept_language 2.0.5

       Installing http_accept_language 2.0.5

       Fetching puma 3.12.1

       Installing puma 3.12.1 with native extensions

       Fetching rails_serve_static_assets 0.0.5

       Installing rails_serve_static_assets 0.0.5

       Fetching rails_stdout_logging 0.0.5

       Installing rails_stdout_logging 0.0.5

       Fetching rb-fsevent 0.10.3

       Installing rb-fsevent 0.10.3

       Fetching tilt 2.0.9

       Installing tilt 2.0.9

       Fetching tzinfo 1.2.5

       Installing tzinfo 1.2.5

       Fetching nokogiri 1.10.3

       Installing nokogiri 1.10.3 with native extensions

       Fetching i18n 1.6.0

       Installing i18n 1.6.0

       Fetching rack-test 0.6.3

       Installing rack-test 0.6.3

       Fetching sprockets 3.7.2

       Installing sprockets 3.7.2

       Fetching websocket-driver 0.6.5

       Installing websocket-driver 0.6.5 with native extensions

       Fetching mail 2.7.1

       Installing mail 2.7.1

       Fetching addressable 2.6.0

       Installing addressable 2.6.0

       Fetching autoprefixer-rails 9.5.1

       Fetching uglifier 4.1.20

       Installing autoprefixer-rails 9.5.1

       Installing uglifier 4.1.20

       Fetching coffee-script 2.4.1

       Installing coffee-script 2.4.1

       Fetching commander-fastlane 4.4.6

       Fetching faraday 0.15.4

       Installing commander-fastlane 4.4.6

       Installing faraday 0.15.4

       Fetching mime-types 3.2.2

       Installing mime-types 3.2.2

       Fetching representable 3.0.4

       Fetching unf 0.1.4

       Installing representable 3.0.4

       Fetching simctl 1.6.5

       Installing unf 0.1.4

       Installing simctl 1.6.5

       Fetching terminal-table 1.8.0

       Installing terminal-table 1.8.0

       Fetching tty-spinner 0.9.1

       Installing tty-spinner 0.9.1

       Fetching xcodeproj 1.10.0

       Installing xcodeproj 1.10.0

       Fetching xcpretty 0.3.0

       Installing xcpretty 0.3.0

       Fetching sassc 2.0.1

       Installing sassc 2.0.1 with native extensions

       Fetching rb-inotify 0.10.0

       Installing rb-inotify 0.10.0

       Fetching rails_12factor 0.0.3

       Installing rails_12factor 0.0.3

       Fetching activesupport 5.0.7.2

       Installing activesupport 5.0.7.2

       Fetching loofah 2.2.3

       Installing loofah 2.2.3

       Fetching faraday_middleware 0.13.1

       Installing faraday_middleware 0.13.1

       Fetching signet 0.11.0

       Installing signet 0.11.0

       Fetching google-cloud-env 1.2.0

       Installing google-cloud-env 1.2.0

       Fetching domain_name 0.5.20180417

       Installing domain_name 0.5.20180417

       Fetching sass-listen 4.0.0

       Installing sass-listen 4.0.0

       Fetching xcpretty-travis-formatter 1.0.0

       Installing xcpretty-travis-formatter 1.0.0

       Fetching rails-html-sanitizer 1.0.4

       Fetching googleauth 0.6.7

       Installing rails-html-sanitizer 1.0.4

       Installing googleauth 0.6.7

       Fetching google-cloud-core 1.3.0

       Installing google-cloud-core 1.3.0

       Fetching http-cookie 1.0.3

       Fetching sass 3.7.4

       Installing http-cookie 1.0.3

       Installing sass 3.7.4

       Fetching rails-dom-testing 2.0.3

       Installing rails-dom-testing 2.0.3

       Fetching globalid 0.4.2

       Installing globalid 0.4.2

       Fetching activemodel 5.0.7.2

       Installing activemodel 5.0.7.2

       Fetching google-api-client 0.23.9

       Fetching faraday-cookie_jar 0.0.6

       Installing faraday-cookie_jar 0.0.6

       Fetching actionview 5.0.7.2

       Installing actionview 5.0.7.2

       Fetching activejob 5.0.7.2

       Installing activejob 5.0.7.2

       Fetching activerecord 5.0.7.2

       Installing activerecord 5.0.7.2

       Installing google-api-client 0.23.9

       Fetching actionpack 5.0.7.2

       Installing actionpack 5.0.7.2

       Fetching actioncable 5.0.7.2

       Installing actioncable 5.0.7.2

       Fetching actionmailer 5.0.7.2

       Installing actionmailer 5.0.7.2

       Fetching railties 5.0.7.2

       Installing railties 5.0.7.2

       Fetching sprockets-rails 3.2.1

       Installing sprockets-rails 3.2.1

       Fetching coffee-rails 4.1.1

       Installing coffee-rails 4.1.1

       Fetching jquery-rails 4.3.3

       Installing jquery-rails 4.3.3

       Fetching rails 5.0.7.2

       Installing rails 5.0.7.2

       Fetching sass-rails 5.0.7

       Installing sass-rails 5.0.7

       Fetching google-cloud-storage 1.16.0

       Installing google-cloud-storage 1.16.0

       Fetching fastlane 2.126.0

       Installing fastlane 2.126.0

       Fetching bootstrap-sass 3.4.1

       Installing bootstrap-sass 3.4.1

       Bundle complete! 19 Gemfile dependencies, 123 gems now installed.

       Gems in the groups development and test were not installed.

       Bundled gems are installed into `./vendor/bundle`

       Post-install message from i18n:

       

       HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.

       But that may break your application.

       

       Please check your Rails app for 'config.i18n.fallbacks = true'.

       If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be

       'config.i18n.fallbacks = [I18n.default_locale]'.

       If not, fallbacks will be broken in your app by I18n 1.1.x.

       

       For more info see:

       https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

       

       Post-install message from sass:

       

       Ruby Sass has reached end-of-life and should no longer be used.

       

       * If you use Sass as a command-line tool, we recommend using Dart Sass, the new

         primary implementation: https://sass-lang.com/install

       

       * If you use Sass as a plug-in for a Ruby web framework, we recommend using the

         sassc gem: https://github.com/sass/sassc-ruby#readme

       

       * For more details, please refer to the Sass blog:

         https://sass-lang.com/blog/posts/7828841

       

       Bundle completed (171.57s)

       Cleaning up the bundler cache.

-----> Installing node-v10.15.3-linux-x64

-----> Detecting rake tasks

 !

 !     Could not detect rake tasks

 !     ensure you can run `$ bundle exec rake -P` against your app

 !     and using the production group of your Gemfile.

 !     Activating bundler (2.0.1) failed:

 !     Could not find 'bundler' (2.0.1) required by your /tmp/build_450b956d8551277fbb2279458df16de6/Gemfile.lock.

 !     To update to the latest version installed on your system, run `bundle update --bundler`.

 !     To install the missing version, run `gem install bundler:2.0.1`

 !     Checked in 'GEM_PATH=vendor/bundle/ruby/2.5.0', execute `gem env` for more information

 !     

 !     To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`

 !

/app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)

ensure you can run `$ bundle exec rake -P` against your app

and using the production group of your Gemfile.

Activating bundler (2.0.1) failed:

Could not find 'bundler' (2.0.1) required by your /tmp/build_450b956d8551277fbb2279458df16de6/Gemfile.lock.

To update to the latest version installed on your system, run `bundle update --bundler`.

To install the missing version, run `gem install bundler:2.0.1`

Checked in 'GEM_PATH=vendor/bundle/ruby/2.5.0', execute `gem env` for more information

To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:866:in `rake'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:84:in `block (2 levels) in run_assets_precompile_rake_task'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:134:in `log'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:78:in `block in run_assets_precompile_rake_task'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:77:in `run_assets_precompile_rake_task'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:107:in `block (2 levels) in compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:887:in `allow_git'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:101:in `block in compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:90:in `compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails2.rb:62:in `block in compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails2.rb:60:in `compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails3.rb:42:in `block in compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails3.rb:41:in `compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:41:in `block in compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:40:in `compile'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/bin/support/ruby_compile:20:in `block (2 levels) in <main>'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:134:in `log'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/bin/support/ruby_compile:19:in `block in <main>'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:35:in `block in trace'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:35:in `trace'

	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/bin/support/ruby_compile:15:in `<main>'

 !     Push rejected, failed to compile Ruby app.

 !     Push failed
```

**Comment by marbetschar** [comment]
Is there anything I can help with to get vanilla deployment to Heroku working again?

**Comment by marbetschar** [comment]
Anyone and/or anything?

**Comment by marbetschar** [comment]
How to deploy fastlane boarding to Heroku? Is it even possible to use boarding as of now - or is it broken since the last Apple API changes?

**Comment by marbetschar** [comment]
Stumbled upon the possibility to create a public link in TestFlight - somehow missed that option. Will use this from now on. In case anyone else missed it too:

https://developer.apple.com/news/?id=09262018a
