### ISSUE TITLE
bundler 2.0.1 issue

### ISSUE THREAD

**Issue by JoukoTyni** [fastlane/boarding#252]
Hi, we cant use the direct links from TestFlight in alpha and now have the app has been down for a while and I'd like to fix it, but when I tried to update the fastlane and even tried creating new app through the easy links in this project page but they all fail in this same issue. 

remote:        Installing bootstrap-sass 3.4.1
remote:        Bundle complete! 19 Gemfile dependencies, 123 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Post-install message from i18n:
remote:
remote:        HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
remote:        But that may break your application.
remote:
remote:        Please check your Rails app for 'config.i18n.fallbacks = true'.
remote:        If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
remote:        'config.i18n.fallbacks = [I18n.default_locale]'.
remote:        If not, fallbacks will be broken in your app by I18n 1.1.x.
remote:
remote:        For more info see:
remote:        https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
remote:
remote:        Post-install message from sass:
remote:
remote:        Ruby Sass has reached end-of-life and should no longer be used.
remote:
remote:        * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
remote:          primary implementation: https://sass-lang.com/install
remote:
remote:        * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
remote:          sassc gem: https://github.com/sass/sassc-ruby#readme
remote:
remote:        * For more details, please refer to the Sass blog:
remote:          https://sass-lang.com/blog/posts/7828841
remote:
remote:        Bundle completed (162.93s)
remote:        Cleaning up the bundler cache.
remote: -----> Installing node-v10.15.3-linux-x64
remote: -----> Detecting rake tasks
remote:
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     Activating bundler (2.0.1) failed:
remote:  !     Could not find 'bundler' (2.0.1) required by your /tmp/build_4bddf08f954368810a34eedf218d6064/Gemfile.lock.
remote:  !     To update to the latest version installed on your system, run `bundle update --bundler`.
remote:  !     To install the missing version, run `gem install bundler:2.0.1`
remote:  !     Checked in 'GEM_PATH=vendor/bundle/ruby/2.5.0', execute `gem env` for more information
remote:  !
remote:  !     To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`
remote:  !
remote: /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: Activating bundler (2.0.1) failed:
remote: Could not find 'bundler' (2.0.1) required by your /tmp/build_4bddf08f954368810a34eedf218d6064/Gemfile.lock.
remote: To update to the latest version installed on your system, run `bundle update --bundler`.
remote: To install the missing version, run `gem install bundler:2.0.1`

**Comment by janpio** [comment]
> ```
> remote: To install the missing version, run `gem install bundler:2.0.1`
> ```

I assume you tried that?

**Comment by JoukoTyni** [comment]
Yes I tried to install locally and it does not make any difference for the old app. I tried to create a completely new one too and It fails for the https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Ffastlane%2Fboarding&template=https%3A%2F%2Fgithub.com%2Ffastlane%2Fboarding build that is done in the cloud afaik

**Comment by jhandguy** [comment]
I'm also seeing this, it does not work when deploying on Heroku.

**Comment by mjmaix** [comment]
Are there workarounds? Ty

**Comment by brunitob** [comment]
1) Download repo
2) heroku login && heroku create
3) heroku buildpacks:set https://github.com/bundler/heroku-buildpack-bundler2
4) git push heroku master

**Comment by mjmaix** [comment]
@brunitob great that works! Thank you.

Don't forget to add env after heroku create, :) `ITC_APP_ID`, `ITC_USER`, `ITC_PASSWORD`

**Comment by KrisztinaWiseman** [comment]
Found this on Heroku's page (https://devcenter.heroku.com/articles/bundler-version#known-upgrade-issues):
Many people are hitting issue which is only triggered when a new Bundler version is released. It happens because of a bug in Rubygems, and can be fixed by upgrading to 2.5.5+ or 2.6.3+.

Bundler 2.0.1
1) If you are deploying with Ruby 2.6.0 then you’ll get an error when your dyno or a release phase command trys to execute a bundle command:

remote: Bundler::LockfileError: You must use Bundler 2 or greater with this lockfile.
remote:   /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version'
remote:   /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
remote:   /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `new'

This is due to the built-in bundler integration that ships with Ruby 2.6.0. This bug is fixed in 2.6.1. If you hit the above error message with bundler 2.0.1, then please upgrade your Ruby version to use 2.6.1.

2) When using binstubs to run a command instead of bundle exec the wrong version of Bundler can get activated when using Ruby 2.6.x. This bug is reported to Ruby Core and will be fixed when Ruby 2.6.3 is released.

In the short term, the workaround is to ensure all commands in the Procfile and app.json are prefaced with bundle exec. For example:

web: bundle exec bin/rails server -p $PORT -e $RAILS_ENV
worker: bundle exec sidekiq -C config/sidekiq.yml
Technically this bug was fixed with 2.6.2 but there are other bugs with that version so we recommend 2.6.3+.

3) Ruby 2.5.x does not work with Bundler 2 unless the EXACT same version of bundler is specified in the Gemfile.lock.

**Comment by KrisztinaWiseman** [comment]
As per the above advice I upgraded to ruby 2.6.3 and it solved the problem.

**Comment by rogerluan** [comment]
Full instructions, step-by-step, are:

1. `git clone git@github.com:fastlane/boarding.git`
1. `cd boarding`
1. `heroku login`
1. `heroku create`
1. `heroku buildpacks:set https://github.com/bundler/heroku-buildpack-bundler2`
1. `heroku config:set ITC_APP_ID=your_add_id`
1. `heroku config:set ITC_USER=your_itunes_connect_username`
1. `heroku config:set ITC_PASSWORD=your_itunes_connect_password`
1. `heroku config:set ITC_TOKEN=your_password_to_protect_boarding`
1. `git push heroku master`
1. `heroku apps:rename your_app_name`
1. Visit https://your_app_name.herokuapp.com/ to see your site up and running
