### ISSUE TITLE
Could not fetch the login URL from iTunes Connect, the server might be down

### ISSUE THREAD

**Issue by sawteeth** [fastlane/boarding#41]
Hi!  Love this project and want to use it so badly, but when trying to use locally, I get this error... My username, password and app ID are all set... Is it a problem with me? Or boarding?  Thanks for any help!

```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Completed 500 Internal Server Error in 7224ms

RuntimeError (Could not fetch the login URL from iTunes Connect, the server might be down):
  app/controllers/invite_controller.rb:131:in `login'
  app/controllers/invite_controller.rb:111:in `app'
  app/controllers/invite_controller.rb:123:in `block in app_metadata'
  app/controllers/invite_controller.rb:121:in `app_metadata'
  app/controllers/invite_controller.rb:135:in `set_app_details'


  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.2ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (45.6ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.3ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.2ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (48.3ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.5ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/sawteeth/.rvm/gems/ruby-2.2.3@global/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (106.9ms)
```

**Comment by sawteeth** [comment]
In regards to the `SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed` error, I have tried fixing it about 10 different ways -- so I don't think it's my computer?

**Comment by KrauseFx** [comment]
Could you try https://github.com/fastlane/fastlane/blob/master/docs/FAQs.md#im-getting-an-ssl-error

**Comment by sawteeth** [comment]
@KrauseFx thanks for the link.  Pretty sure I did that already, but I'll give it a try and let you know.

**Comment by sawteeth** [comment]
Hey -- I'm using the latest SSL I think  (I get this in terminal):

```
Error: openssl 1.0.2d_1 already installed         #from homebrew
```

Getting the same error.

**Comment by sawteeth** [comment]
Fixed it!  I updated to latest fastlane, and reset all ruby gems.
