### ISSUE TITLE
fatal error on user signup

### ISSUE THREAD

**Issue by AndrewSB** [fastlane/boarding#53]
I followed the instructions in the README, but I'm getting an error whenever I try to submit a new tester. Here are the logs from Heroku

```
2015-12-08T01:02:45.312906+00:00 app[web.1]: I, [2015-12-08T01:02:44.337911 #3]  INFO -- : Going to create a new tester: a@ndrew.me - Andrew Breckenridge
2015-12-08T01:02:45.312908+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/spaceship-0.15.1/lib/spaceship/tunes/tunes_client.rb:718:in `testers'
2015-12-08T01:02:45.312908+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/spaceship-0.15.1/lib/spaceship/tunes/tester.rb:74:in `all'
2015-12-08T01:02:45.312906+00:00 app[web.1]: F, [2015-12-08T01:02:45.312653 #3] FATAL -- : #<Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"}>
2015-12-08T01:02:45.312910+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2015-12-08T01:02:45.312909+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/spaceship-0.15.1/lib/spaceship/tunes/tester.rb:81:in `find'
2015-12-08T01:02:45.312909+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:58:in `submit'
2015-12-08T01:02:45.312910+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
2015-12-08T01:02:45.312911+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
2015-12-08T01:02:45.312911+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2015-12-08T01:02:45.312911+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
2015-12-08T01:02:45.312912+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
2015-12-08T01:02:45.312912+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2015-12-08T01:02:45.312913+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
2015-12-08T01:02:45.312913+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
2015-12-08T01:02:45.312913+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
2015-12-08T01:02:45.312914+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
2015-12-08T01:02:45.312924+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2015-12-08T01:02:45.312925+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
2015-12-08T01:02:45.312928+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
2015-12-08T01:02:45.312929+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2015-12-08T01:02:45.312929+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-12-08T01:02:45.312929+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
2015-12-08T01:02:45.312930+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
2015-12-08T01:02:45.312930+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2015-12-08T01:02:45.312931+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2015-12-08T01:02:45.312931+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
2015-12-08T01:02:45.312931+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
2015-12-08T01:02:45.312932+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
2015-12-08T01:02:45.312932+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2015-12-08T01:02:45.312932+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
2015-12-08T01:02:45.312933+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
2015-12-08T01:02:45.312933+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
2015-12-08T01:02:45.312933+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2015-12-08T01:02:45.312934+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
2015-12-08T01:02:45.312935+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
2015-12-08T01:02:45.312934+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2015-12-08T01:02:45.312935+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
2015-12-08T01:02:45.312935+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
2015-12-08T01:02:45.312936+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
2015-12-08T01:02:45.312936+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
2015-12-08T01:02:45.312937+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2015-12-08T01:02:45.312937+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2015-12-08T01:02:45.312938+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
2015-12-08T01:02:45.312938+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
2015-12-08T01:02:45.312939+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
2015-12-08T01:02:45.312939+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2015-12-08T01:02:45.312939+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2015-12-08T01:02:45.312940+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
2015-12-08T01:02:45.312941+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
2015-12-08T01:02:45.312941+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
2015-12-08T01:02:45.312941+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2015-12-08T01:02:45.312942+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2015-12-08T01:02:45.312942+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2015-12-08T01:02:45.312942+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2015-12-08T01:02:45.312943+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2015-12-08T01:02:45.312943+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
2015-12-08T01:02:45.312955+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2015-12-08T01:02:45.312954+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:22:in `call'
2015-12-08T01:02:45.312955+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2015-12-08T01:02:45.312954+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2015-12-08T01:02:45.312955+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2015-12-08T01:02:45.312971+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
2015-12-08T01:02:45.312971+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
2015-12-08T01:02:45.312956+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
2015-12-08T01:02:45.312956+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2015-12-08T01:02:45.312973+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
2015-12-08T01:02:45.312972+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
2015-12-08T01:02:45.312972+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
2015-12-08T01:02:45.312974+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
2015-12-08T01:02:45.312972+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
2015-12-08T01:02:45.312973+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
```

**Comment by TomCarey** [comment]
+1

**Comment by Gladkov-Art** [comment]
I had similar problem, and changing to the main account resolved this issue for me too. 
But I'm a bit disappointed that I have to disclose credentials for account that has some other released applications.

**Comment by alex-schwartzman** [comment]
I have the same problem. Nothing works unless I grant admin rights to the user, specified in the app configuration. I'll try to fix it this weekend and send you pull request.

**Comment by bencollier** [comment]
Same issue here, using an iTunes Connect 'technical' account;

```
Going to create a new tester: ben@123.com - Ben Collier
2015-12-11T13:38:30.442709+00:00 app[web.1]: F, [2015-12-11T13:38:30.442394 #3] FATAL -- : #<Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}>
2015-12-11T13:38:30.442710+00:00 app[web.1]: F, [2015-12-11T13:38:30.442600 #3] FATAL -- : /app/vendor/bundle/ruby/2.2.0/gems/spaceship-0.15.1/lib/spaceship/client.rb:263:in `parse_response'
```

No 2FA enabled.

**Comment by revile** [comment]
Same issue using an 'App Manager' account. Would prefer not to have to use the main account for this

**Comment by KrauseFx** [comment]
You'll need to update `spaceship` to the latest version. Please follow the update guide on the README to update to the latest `spaceship`

**Comment by revile** [comment]
I installed a fresh version about 8 hours ago, has there been changes since then?

**Comment by alex-schwartzman** [comment]
Deleted the boarding app from heroku
Installed it from scratch
Expected that spaceship dependency will be resolved to the latest version (don't know how it works however)
Checked.

Still I experience the same behavior as before.

```
2016-01-05T11:19:27.866158+00:00 app[web.1]: I, [2016-01-05T11:17:12.432924 #3]  INFO -- : Completed 200 OK in 3ms (Views: 2.9ms)
2016-01-05T11:19:27.866170+00:00 app[web.1]: I, [2016-01-05T11:19:25.939892 #3]  INFO -- : Processing by InviteController#submit as HTML
2016-01-05T11:19:27.866176+00:00 app[web.1]: F, [2016-01-05T11:19:27.866066 #3] FATAL -- : /app/vendor/bundle/ruby/2.2.0/gems/spaceship-0.19.0/lib/spaceship/client.rb:268:in `parse_response'
2016-01-05T11:19:27.866177+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/spaceship-0.19.0/lib/spaceship/tunes/tunes_client.rb:693:in `testers'
2016-01-05T11:19:27.866180+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:58:in `submit'
2016-01-05T11:19:27.866182+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
2016-01-05T11:19:27.866183+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2016-01-05T11:19:27.866184+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
2016-01-05T11:19:27.866185+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2016-01-05T11:19:27.866186+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
2016-01-05T11:19:27.866187+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
2016-01-05T11:19:27.866187+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
2016-01-05T11:19:27.866189+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-01-05T11:19:27.866189+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
2016-01-05T11:19:27.866190+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
2016-01-05T11:19:27.866192+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
2016-01-05T11:19:27.866193+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-01-05T11:19:27.866199+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2016-01-05T11:19:27.866201+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
2016-01-05T11:19:27.866202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
2016-01-05T11:19:27.866203+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
2016-01-05T11:19:27.866204+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2016-01-05T11:19:27.866207+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2016-01-05T11:19:27.866208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
2016-01-05T11:19:27.866209+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
2016-01-05T11:19:27.866210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
2016-01-05T11:19:27.866212+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
2016-01-05T11:19:27.866212+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
2016-01-05T11:19:27.866216+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
2016-01-05T11:19:27.866223+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2016-01-05T11:19:27.866233+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2016-01-05T11:19:27.866234+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
2016-01-05T11:19:27.866234+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
2016-01-05T11:19:27.866237+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
2016-01-05T11:19:27.866228+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-01-05T11:19:27.866228+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
2016-01-05T11:19:27.866233+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2016-01-05T11:19:27.866234+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
2016-01-05T11:19:27.866235+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
2016-01-05T11:19:27.866238+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
2016-01-05T11:19:27.866239+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
2016-01-05T11:19:27.866228+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-01-05T11:19:27.866228+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
2016-01-05T11:19:27.866234+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
2016-01-05T11:19:27.866235+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
2016-01-05T11:19:27.866236+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
2016-01-05T11:19:27.866237+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
2016-01-05T11:19:27.866238+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
2016-01-05T11:19:27.866228+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-01-05T11:19:27.866233+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2016-01-05T11:19:27.866235+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
2016-01-05T11:19:27.866237+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
2016-01-05T11:19:27.866238+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
```

**Comment by iosdeveloper** [comment]
^ Any idea @KrauseFx?

**Comment by KrauseFx** [comment]
Make sure to use the latest version of `spaceship` 0.19.1

**Comment by revile** [comment]
This still doesn't work @KrauseFx 

1. Installing from scratch still results in spaceship 0.19.0 being installed, I guess since the `Gemfile.lock` specifies that version
2. Even after manually updating to the latest (now `0.19.3`) I get the same error when using an account that is an App Manager for the app in question

Any ideas?

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/boarding/commit/82415d33cf9b78a1a57abf75ab71a9abe2a3ae2d, could you try that? :+1:

**Comment by patoroco** [comment]
I just install it (with spaceship 0.19.3 as you did in @82415d3), and it returns me same error with an specific account for that :(

**Comment by nick2060** [comment]
Any update on this? Am getting the same issue when signing up on heroku boarding app. The ITC account who created the app is an admin and I am definitely using the newest version of spaceship. @KrauseFx

**Comment by Draknek** [comment]
I'm experiencing this bug with a fresh install of boarding - trying to use a non-admin account with "app manager" permissions. The signup form appears fine, but when you submit it gives an error.

**Comment by KrauseFx** [comment]
@Draknek boarding only supports Admin accounts currently

**Comment by Draknek** [comment]
@KrauseFx Why is that? App manager accounts should have the required permissions I think, and it's reasonable to not want to share login credentials for an admin account.

I'm happy to take a look at the code if this might be a fixable problem?

**Comment by KrauseFx** [comment]
@Draknek Yes, agreed. Feel free to dive into the spaceship code. One of the requests (I think `listTeam`) requires admin privileges, so that's why spaceship fails.
Your role is App Manager, and boarding doesn't work, right? If you don't get it to work, let me know, I might be able to look into this over the next few days/weeks 👍

**Comment by Draknek** [comment]
Okay thanks. I'm not familiar with the codebase but I'll dive in and see if I manage to get anywhere.

And yeah, this is definitely related to roles: with the App Manager role boarding doesn't work, but with an admin role it does.

**Comment by taquitos** [comment]
This should work now, https://github.com/fastlane/boarding/pull/150 was merged a little while ago to enable `App Manager` to be used along with `Admin`
