### ISSUE TITLE
"Can't verify CSRF token authenticity" when some people sign up

### ISSUE THREAD

**Issue by alecgorge** [fastlane/boarding#59]
I haven't been able to reproduce this myself, but I have gotten sporadic reports from users that they get an error saying "The change you wanted was rejected" and maybe this will help other people chip in information.

Is there any advice I can give the users? If not, can we add a flag to disable CSRF checking?

In the logs I see things like this:

```
2016-02-03T01:15:17.164759041Z app[web.1]: Started POST "/submit" for xx.xx.xx.xx at 2016-02-03 01:15:17 +0000
2016-02-03T01:15:17.166967316Z app[web.1]: Processing by InviteController#submit as HTML
2016-02-03T01:15:17.167643721Z app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"N2gcarBfi6AxPgg9/Mu+C8rcBzcXj6f1IEEb0NnxwPTl11wwxlByJWx0wkbAcTMuksjTJiXodKT+uV2wUNct5A==", "first_name"=>"xxx", "last_name"=>"xxx", "email"=>"aaa@bbb.com", "commit"=>"Get Beta Access"}
2016-02-03T01:15:17.168728354Z app[web.1]: Can't verify CSRF token authenticity
2016-02-03T01:15:17.169390154Z app[web.1]: Completed 422 Unprocessable Entity in 2ms
2016-02-03T01:15:17.171051447Z app[web.1]:
2016-02-03T01:15:17.171080946Z app[web.1]: ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
2016-02-03T01:15:17.171097008Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
2016-02-03T01:15:17.171104785Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
2016-02-03T01:15:17.171111834Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
2016-02-03T01:15:17.171119896Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
2016-02-03T01:15:17.171129266Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:164:in `call'
2016-02-03T01:15:17.171136116Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:164:in `block in halting'
2016-02-03T01:15:17.171142912Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
2016-02-03T01:15:17.171157219Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `block in call'
2016-02-03T01:15:17.171192082Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `each'
2016-02-03T01:15:17.171206760Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
2016-02-03T01:15:17.171213518Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
2016-02-03T01:15:17.171219608Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
2016-02-03T01:15:17.171225892Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-02-03T01:15:17.171231777Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
2016-02-03T01:15:17.171237654Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
2016-02-03T01:15:17.171243346Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2016-02-03T01:15:17.171249082Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
2016-02-03T01:15:17.171254863Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-02-03T01:15:17.171260653Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
2016-02-03T01:15:17.171266367Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2016-02-03T01:15:17.171272128Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2016-02-03T01:15:17.171277801Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
2016-02-03T01:15:17.171283706Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
2016-02-03T01:15:17.171289401Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
2016-02-03T01:15:17.171295074Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2016-02-03T01:15:17.171300765Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
2016-02-03T01:15:17.171306470Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
2016-02-03T01:15:17.171312279Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
2016-02-03T01:15:17.171317949Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2016-02-03T01:15:17.171324105Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2016-02-03T01:15:17.171329871Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
2016-02-03T01:15:17.171342817Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
2016-02-03T01:15:17.171349237Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
2016-02-03T01:15:17.171354952Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
2016-02-03T01:15:17.171360733Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
2016-02-03T01:15:17.171397663Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
2016-02-03T01:15:17.171404474Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2016-02-03T01:15:17.171411546Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2016-02-03T01:15:17.171417775Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
2016-02-03T01:15:17.171424002Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
2016-02-03T01:15:17.171429822Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
2016-02-03T01:15:17.171435642Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2016-02-03T01:15:17.171441381Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2016-02-03T01:15:17.171447393Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
2016-02-03T01:15:17.173015350Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
2016-02-03T01:15:17.173070828Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
2016-02-03T01:15:17.173179818Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-02-03T01:15:17.173206122Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2016-02-03T01:15:17.173333575Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2016-02-03T01:15:17.173363369Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2016-02-03T01:15:17.173464959Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2016-02-03T01:15:17.173491561Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
2016-02-03T01:15:17.173595913Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
2016-02-03T01:15:17.173621789Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2016-02-03T01:15:17.173727737Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
2016-02-03T01:15:17.173788517Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
2016-02-03T01:15:17.173929489Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
2016-02-03T01:15:17.173962688Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2016-02-03T01:15:17.174067759Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2016-02-03T01:15:17.174095572Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2016-02-03T01:15:17.174192054Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-02-03T01:15:17.174217734Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
2016-02-03T01:15:17.174314899Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2016-02-03T01:15:17.174339597Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
2016-02-03T01:15:17.174440163Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
2016-02-03T01:15:17.174465511Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/configuration.rb:81:in `call'
2016-02-03T01:15:17.174562612Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
2016-02-03T01:15:17.174589216Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
2016-02-03T01:15:17.174712108Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
2016-02-03T01:15:17.174738562Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
2016-02-03T01:15:17.174848159Z app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by arabold** [comment]
I'm seeing the same issue for a couple of people, but couldn't reproduce this myself. Any idea what could cause this?

**Comment by AlexEKoren** [comment]
It's only happening for me when users use Safari actually...
