### ISSUE TITLE
Boarding usage regarding the app approbation by apple

### ISSUE THREAD

**Issue by dayervi** [fastlane/boarding#66]
not really an issue but I has a doubt and I found no information about it.

I have an app which is still "waiting for review" and has never been publish on the app store. The app has been approved for beta testing but it's impossible to create a new tester through the form:

> 2016-03-17T15:39:08.481772 #19044]  INFO -- : Going to create a new tester: xxx@xxxx.xx - Xxxxx Xxxxxxx
[2016-03-17T15:39:10.928867 #19044] FATAL -- : # < NameError: uninitialized constant InviteController::Helper >
[2016-03-17T15:39:10.929063 #19044] FATAL -- : /var/app/current/app/controllers/invite_controller.rb:58:in `submit'

It seems that the app crash when it test if the email already exist as external tester on itunes connect. Required environments variables are right but it's doesn't work. I think that I have to wait until the approval for the App store, can anyone confirm that?

**Comment by aral** [comment]
I got this while testing from localhost – same details worked from the deployment server. Not sure if that’s a factor as I haven’t looked into it at depth (trying to fix something else at the moment).

**Comment by acerbetti** [comment]
I'm seeing the same issue on heroku, brand new deployment from today. 

```
2016-04-08T18:22:06.183231+00:00 app[web.1]: Going to create a new tester: test@test.com - First Last
2016-04-08T18:22:07.993555+00:00 heroku[router]: at=info method=GET path="/assets/application-7c2401d58a372b5108ef153ec0175bb98d05e1148a51424a3b0e27745afd3106.css" host=XXX request_id=8842fab8-81a4-42e2-86c1-c9bbd8d22624 fwd="4.16.196.65" dyno=web.1 connect=1ms service=2ms status=304 bytes=119
2016-04-08T18:22:07.873662+00:00 heroku[router]: at=info method=POST path="/submit" host=XXX request_id=e32e43e4-c0d2-48ff-acd2-8e5be2421db7 fwd="4.16.196.65" dyno=web.1 connect=1ms service=1681ms status=200 bytes=2138
2016-04-08T18:22:07.850859+00:00 app[web.1]: #<NameError: uninitialized constant InviteController::Helper>
2016-04-08T18:22:07.850985+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:60:in `submit'
2
...
```

**Comment by blumersolutions** [comment]
I'm experiencing this same exact issue. BUT, is only caused with a specific Apple account.
It works OK, the tester is added to the public beta testing IF I'm using my account details. BUT if I use client's account details I'm getting the same error message described here:
"# < NameError: uninitialized constant InviteController::Helper > ..."
Could you confirm if this is a known issue and if there's a fix/workaround for this?

Thanks!
