### ISSUE TITLE
New Heroku App Failing

### ISSUE THREAD

**Issue by sirnacnud** [fastlane/boarding#71]
I deployed boarding to Heroku and set the environment variables correctly. When I go the the site, I get the `We're sorry, but something went wrong` error. I checked the logs and it seems like it is failing to log in, but there isn't a clear error. I have two factor authentication enabled for my apple id, could this be causing the problem?

Below is what is in the log, it appears to be logging some kind of cookie related to the authentication, which I have removed.

    2016-04-04T10:34:33.614035+00:00 app[web.1]: Spaceship::TunesClient::ITunesConnectError ({}
    2016-04-04T10:34:33.614039+00:00 app[web.1]: COOKIE REMOVED):
    2016-04-04T10:34:33.614040+00:00 app[web.1]:   app/controllers/invite_controller.rb:140:in `login'
    2016-04-04T10:34:33.614040+00:00 app[web.1]:   app/controllers/invite_controller.rb:120:in `app'
    2016-04-04T10:34:33.614041+00:00 app[web.1]:   app/controllers/invite_controller.rb:132:in `block in app_metadata'
    2016-04-04T10:34:33.614042+00:00 app[web.1]:   app/controllers/invite_controller.rb:130:in `app_metadata'
    2016-04-04T10:34:33.614044+00:00 app[web.1]: 
    2016-04-04T10:34:33.612651+00:00 app[web.1]: Completed 500 Internal Server Error in 476ms

**Comment by KrauseFx** [comment]
> I have two factor authentication enabled for my apple id, could this be causing the problem?

Yes, that's the problem, currently 2 step is not supported. However you can easily use the latest master from `spaceship`, since it's already there.

You can follow https://github.com/fastlane/fastlane/issues/3503
