### ISSUE TITLE
NoMethodError (undefined method `apple_id')

### ISSUE THREAD

**Issue by denbec** [fastlane/boarding#78]
Hey guys,

I just tried out boarding and deployed to Heroku (which I'm new to...).

After entering the data the script runs through successfully but visiting the site shows an error. The log has the following to say:

```
2016-05-13T08:54:29.350956+00:00 app[web.1]: Completed 500 Internal Server Error in 2340ms
2016-05-13T08:54:29.351550+00:00 app[web.1]: 
2016-05-13T08:54:29.351560+00:00 app[web.1]: NoMethodError (undefined method 'apple_id' for nil:NilClass):
2016-05-13T08:54:29.351565+00:00 app[web.1]: 
2016-05-13T08:54:29.351563+00:00 app[web.1]:   app/controllers/invite_controller.rb:132:in 'block in app_metadata'
2016-05-13T08:54:29.350956+00:00 app[web.1]: Completed 500 Internal Server Error in 2340ms
2016-05-13T08:54:29.351550+00:00 app[web.1]: 
2016-05-13T08:54:29.351564+00:00 app[web.1]:   app/controllers/invite_controller.rb:145:in 'set_app_details'
2016-05-13T08:54:29.351563+00:00 app[web.1]:   app/controllers/invite_controller.rb:130:in 'app_metadata'
2016-05-13T08:54:29.351562+00:00 app[web.1]:   app/controllers/invite_controller.rb:124:in 'app'
2016-05-13T08:54:29.351565+00:00 app[web.1]: 
2016-05-13T08:54:29.351561+00:00 app[web.1]:   app/controllers/invite_controller.rb:112:in 'block in apple_id'
2016-05-13T08:54:29.351563+00:00 app[web.1]:   app/controllers/invite_controller.rb:132:in 'block in app_metadata'
2016-05-13T08:54:29.351565+00:00 app[web.1]: 
2016-05-13T08:54:29.350956+00:00 app[web.1]: Completed 500 Internal Server Error in 2340ms
2016-05-13T08:54:29.351560+00:00 app[web.1]: NoMethodError (undefined method 'apple_id' for nil:NilClass):
2016-05-13T08:54:29.351564+00:00 app[web.1]:   app/controllers/invite_controller.rb:145:in 'set_app_details'
2016-05-13T08:54:29.351563+00:00 app[web.1]:   app/controllers/invite_controller.rb:130:in 'app_metadata'
2016-05-13T08:57:35.284705+00:00 app[web.1]: Started GET "/" for 46.252.131.226 at 2016-05-13 08:57:35 +0000
2016-05-13T08:57:35.285333+00:00 app[web.1]: Processing by InviteController#index as HTML
```

Any idea?

**Comment by denbec** [comment]
I provided an app identifier, not the apple_id. Maybe spaceship changed, but it seems like the apple_id can't be retrieved from iTunes.
Using the Apple ID helped and the site is now correctly showing up. Entering a user doesn't work, but I'll look into that now.

**Comment by taquitos** [comment]
Is this still an issue? It's been quite a long while.

**Comment by Eths** [comment]
@taquitos yes, trying to update: 

`NoMethodError: undefined method `apple_id' for nil:NilClass
remote:        /tmp/build_f878674cfa391aa9aa859f440f00e0e7/app/services/boarding_service.rb:81:in `ensure_values'
remote:        /tmp/build_f878674cfa391aa9aa859f440f00e0e7/app/services/boarding_service.rb:32:in `initialize'
remote:        /tmp/build_f878674cfa391aa9aa859f440f00e0e7/config/initializers/services.rb:1:in `new'
remote:        /tmp/build_f878674cfa391aa9aa859f440f00e0e7/config/initializers/services.rb:1:in `<top (required)>'`

**Comment by taquitos** [comment]
@Eths I'm looking into it now, thanks for testing it out!

**Comment by taquitos** [comment]
Ahh, ok, here we go: https://github.com/fastlane/boarding/pull/141

It looks like your app with the apple_id you specified wasn't being found and it was causing validation to unintentionally raise an exception. The referenced PR should give you an error message now instead of just failing.

**Comment by Eths** [comment]
Thanks, working fine with my project now
