### ISSUE TITLE
500 error We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by gambitx3x** [fastlane/boarding#94]
Getting this when I deployed after following your steps with the heroku button. It seemed to install perfectly but when opening the app I get the "We're sorry, but something went wrong." error message.
My logs are below the image, not sure what to do. I saw in a related issue someone had an outdated version but mine is direct from the heroku button on the github code page in your readme.

![image](https://cloud.githubusercontent.com/assets/1147298/17948276/1c024888-6a1e-11e6-8ca5-8d269e00fb78.png)

--LOGS--
2016-08-24T21:09:21.835126+00:00 app[web.1]: Completed 500 Internal Server Error in 126ms
2016-08-24T21:09:21.835623+00:00 app[web.1]:   app/controllers/invite_controller.rb:125:in `app'
2016-08-24T21:09:21.835626+00:00 app[web.1]:   app/controllers/invite_controller.rb:150:in `set_app_details'
2016-08-24T21:09:21.835626+00:00 app[web.1]: 
2016-08-24T21:09:21.835625+00:00 app[web.1]:   app/controllers/invite_controller.rb:135:in `app_metadata'
2016-08-24T21:09:21.818506+00:00 heroku[router]: at=info method=GET path="/" host=hurdle-customer-beta.herokuapp.com request_id=a32f118f-f75f-45db-a39a-1f3662f9eb48 fwd="8.31.229.4" dyno=web.1 connect=1ms service=129ms status=500 bytes=1669
2016-08-24T21:11:13.335614+00:00 app[web.1]: Started GET "/" for 8.31.229.4 at 2016-08-24 21:11:13 +0000
2016-08-24T21:11:13.336160+00:00 app[web.1]: Processing by InviteController#index as HTML
2016-08-24T21:11:13.455621+00:00 app[web.1]:   app/controllers/invite_controller.rb:150:in `set_app_details'
2016-08-24T21:11:13.455621+00:00 app[web.1]: 
2016-08-24T21:11:13.440151+00:00 heroku[router]: at=info method=GET path="/" host=hurdle-customer-beta.herokuapp.com request_id=bca36c3f-3432-4ac2-b952-bfaec52b3112 fwd="8.31.229.4" dyno=web.1 connect=2ms service=122ms status=500 bytes=1669
2016-08-24T21:11:14.215861+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=hurdle-customer-beta.herokuapp.com request_id=77453b6e-ab4d-4f9d-9cc0-912a5c834120 fwd="8.31.229.4" dyno=web.1 connect=1ms service=2ms status=200 bytes=143

**Comment by gambitx3x** [comment]
it was a username permissions thing, i figured it out, had to use the master account
